* [[https://github.com/sigmf/SigMF][SigMF]]
:PROPERTIES:
:ID:       f21a6477-6a3f-48f7-8a9e-43f5cf65286c
:END:
#+begin_quote
Sharing sets of recorded signal data is an important part of science
and engineering. It enables multiple parties to collaborate, is often
a necessary part of reproducing scientific results (a requirement of
scientific rigor), and enables sharing data with those who do not have
direct access to the equipment required to capture it.

Unfortunately, these datasets have historically not been very
portable, and there is not an agreed upon method of sharing metadata
descriptions of the recorded data itself. This is the problem that
SigMF solves.

By providing a standard way to describe data recordings, SigMF
facilitates the sharing of data, prevents the "bitrot" of datasets
wherein details of the capture are lost over time, and makes it
possible for different tools to operate on the same dataset, thus
enabling data portability between tools and workflows.
#+end_quote

the-spec: https://github.com/sigmf/SigMF/blob/sigmf-v1.x/sigmf-spec.md
* [[https://www.libvolk.org/][LibVOLK]]
:PROPERTIES:
:ID:       ae34135c-488e-4aff-b795-a4d0d558f22b
:END:
Vector-Optimized Library of Kernels (simd)
* [[https://docs.kernel.org/fb/framebuffer.html][/dev/fb*]]
:PROPERTIES:
:ID:       7819a970-1f37-40a6-985f-905b25a08a4a
:END:
framebuffers, used by fbgrab/fbcat program
* [[https://docs.kernel.org/block/ublk.html][ublk]]
:PROPERTIES:
:ID:       5ccaed39-7055-4a51-ab62-769a73425270
:END:
https://github.com/ming1/ubdsrv
