* NOTE On blocks and devices
:LOGBOOK:
- State "NOTE"       from              [2024-03-02 Sat 21:30]
:END:
[[https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/dev.html][/dev]]
In Linux, everything is a file.

/dev/ contains special device files - usually block or character
device.

major, minor = category, device
0, 5

mknod - create special device files

[[https://www.redhat.com/en/blog/linux-block-devices-hints-debugging-and-new-developments][redhat hints]]

#+begin_src shell
  dd if=/dev/zero of=myfile bs=1M count=32
  losetup --show -f myfile
  ls -al /dev/loop0
  losetup -d /dev/loop0 #teardown
#+end_src

#+begin_src shell
  echo "sup dude" > /dev/loop0
  dd if=/dev/loop0 -bs=1
  dd if=/dev/nvme0 of=/dev/null progress=true
  #pacman -S hdparm
  hdparm -T /dev/nvme0
#+end_src

#+begin_src shell
modprobe scsi_debug add_host=5 max_luns=10 num_tgts=2 dev_size_mb=16
#+end_src

sparsefiles: create with C, dd, or truncate

#+begin_src shell :results output
truncate --help
#+end_src

#+RESULTS:
#+begin_example
Usage: truncate OPTION... FILE...
Shrink or extend the size of each FILE to the specified size

A FILE argument that does not exist is created.

If a FILE is larger than the specified size, the extra data is lost.
If a FILE is shorter, it is extended and the sparse extended part (hole)
reads as zero bytes.

Mandatory arguments to long options are mandatory for short options too.
  -c, --no-create        do not create any files
  -o, --io-blocks        treat SIZE as number of IO blocks instead of bytes
  -r, --reference=RFILE  base size on RFILE
  -s, --size=SIZE        set or adjust the file size by SIZE bytes
      --help        display this help and exit
      --version     output version information and exit

The SIZE argument is an integer and optional unit (example: 10K is 10*1024).
Units are K,M,G,T,P,E,Z,Y,R,Q (powers of 1024) or KB,MB,... (powers of 1000).
Binary prefixes can be used, too: KiB=K, MiB=M, and so on.

SIZE may also be prefixed by one of the following modifying characters:
'+' extend by, '-' reduce by, '<' at most, '>' at least,
'/' round down to multiple of, '%' round up to multiple of.

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation <https://www.gnu.org/software/coreutils/truncate>
or available locally via: info '(coreutils) truncate invocation'
#+end_example

test mkfs.btrfs on 10T dummy block device
#+begin_src shell
  dd if=/dev/zero of=/tmp/bb1 bs=1 count=1 seek=10T
  du -sh /tmp/bb1
  losetup --show -f /tmp/bb1
  mkfs.btrfs /dev/loop0
#+end_src

diagnostics
#+begin_src shell
  iostat # pacman -S sysstat
  blktrace # paru -S blktrace
  iotop # pacman -S iotop
#+end_src

bcc/ trace: Who/which process is executing specific functions against
block devices?

bcc/biosnoop: Which process is accessing the block device, how many
bytes are accessed, which latency for answering the requests?

at the kernel level besides BPF we got kmods and DKMS,

compression/de-duplication can be done via VDO kernel mod

https://en.wikipedia.org/wiki/Dynamic_Kernel_Module_Support

* NOTE save-lisp-and-respawn
:LOGBOOK:
- State "NOTE"       from              [2024-03-02 Sat 22:57]
:END:
#+begin_src lisp
  sb-ext:*save-hooks*
#+end_src

* NOTE syslog for log
:LOGBOOK:
- State "NOTE"       from              [2024-03-03 Sun 16:35]
:END:
sb-posix:
- openlog syslog closelog
- levels: emerg alert crit err warning notice info debug
- setlogmask
