#+title: RDB testbed

We're just about finished with our Lisp ORM based on Elephant which
has changed the interface of OBJ/DB and added a new one for
OBJ/STORE. Both interfaces needed to be implemented.

On the other end we have also built support for merge-operators,
comparators, compaction-filters, and slicetransforms via the ROCKSDB
ffi package. We don't have a clean API for integrating these features
yet.

#+name: load-rdb-playground
#+begin_src lisp :package rdb
(defpkg :rdb/playground
  (:use :core :rt/flamegraph :organ/graph :organ/db))
(in-package :rdb/playground)
(in-readtable :core)
(load-database-backend :rdb)
#+end_src

#+RESULTS: load-rdb-playground
: :RDB

* Tests
:PROPERTIES:
:ID:       7639014a-ff71-4482-855a-05f8c59481e9
:CREATED:  <2026-05-19 Tue 20:35>
:END:
#+call: load-user()
#+begin_src lisp
  (test-system :rdb)
#+end_src

#+RESULTS:
: T
* Flamegraph
:PROPERTIES:
:ID:       4c20c1a5-34ca-4ebc-b3f1-9a40bc0833d3
:CREATED:  <2026-05-19 Tue 20:35>
:END:

#+name: rdb-flamegraph
#+begin_src lisp  :var x=100 y=420 mode=':cpu file="/tmp/rdb-flamegraph"
  (rt/flamegraph:with-flamegraph (file :mode mode)
    (db:with-temp-db (db :open t :close t)
      db
      (dotimes (i x)
        (io/static:with-static-vector (v1 y)
          (loop for i below y
                do (setf (aref v1 i) (random 256))
                do (let ((k (string-to-octets (string (gensym "foo")))))
                     (obj/db:put-key db k v1)
                     (obj/val:get-val db k))))))
    file)
#+end_src

#+RESULTS: rdb-flamegraph
: /tmp/rdb-flamegraph

#+begin_src shell :var file=rdb-flamegraph() output="/tmp/rdb-flamegraph.svg" :results file link :file /tmp/rdb-flamegraph.svg
rm -f $output
flamegraph.pl $file >> $output
#+end_src

#+RESULTS:
[[file:/tmp/rdb-flamegraph.svg]]


#+begin_src lisp :package rdb/playground :results output
;; (profile-rdb-functions)
(sb-sprof:report :type :flat)
;; (sb-profile:report)
#+end_src

#+RESULTS:
#+begin_example

Number of samples:   3500
Sample interval:     0.01 seconds
Total sampling time: 35.0 seconds
Graph cycles:        0
Sampled threads:
   #<THREAD tid=296950 "log-thread" RUNNING {12365C5683}> (144/1048576 bytes, 1 hash buckets)
   #<THREAD tid=349501 "worker" FINISHED values: T {1228028B33}> (1107424/2097152 bytes, 2491 hash buckets)

           Self        Total        Cumul
  Nr  Count     %  Count     %  Count     %    Calls  Function
------------------------------------------------------------------------
   1    760  21.7   1705  48.7    760  21.7        -  (LABELS SB-IMPL::RECURSE :IN SB-INT:GLOBALDB-SXHASHOID)
   2    480  13.7    843  24.1   1240  35.4        -  (LABELS SB-IMPL::EQUAL-NOT-INLINE :IN EQUAL)
   3    256   7.3    256   7.3   1496  42.7        -  (LABELS SB-IMPL::SXHASH-RECURSE :IN SXHASH)
   4    174   5.0    347   9.9   1670  47.7        -  (LAMBDA (&REST SB-INTERPRETER::ARGS) :IN SB-INTERPRETER::APPLICATOR/GENERAL)
   5    145   4.1   1272  36.3   1815  51.9        -  SB-INT:GLOBALDB-SXHASHOID
   6    122   3.5    122   3.5   1937  55.3        -  SXHASH
   7     96   2.7   1856  53.0   2033  58.1        -  SB-ALIEN::COERCE-TO-INTERPRETED-FUNCTION
   8     86   2.5    845  24.1   2119  60.5        -  LET
   9     86   2.5    179   5.1   2205  63.0        -  (SB-INTERPRETER::FAST-GLOBAL-CALL 2)
  10     71   2.0     71   2.0   2276  65.0        -  foreign function try_allocate_small
  11     65   1.9    189   5.4   2341  66.9        -  SB-ALIEN-INTERNALS:COMPUTE-DEPOSIT-LAMBDA
  12     53   1.5    141   4.0   2394  68.4        -  LET*
  13     49   1.4     49   1.4   2443  69.8        -  FPR-SAVE
  14     47   1.3     67   1.9   2490  71.1        -  SB-ALIEN::ALIEN-TYPE-CLASS
  15     43   1.2     43   1.2   2533  72.4        -  SB-INTERPRETER::GET-VAR
  16     42   1.2     42   1.2   2575  73.6        -  TRUNCATE
  17     36   1.0     36   1.0   2611  74.6        -  FPR-RESTORE
  18     33   0.9     33   0.9   2644  75.5        -  SB-KERNEL::INTEGER-/-INTEGER
  19     30   0.9     81   2.3   2674  76.4        -  SB-ALIEN::DEREF-GUTS
  20     30   0.9     73   2.1   2704  77.3        -  (SB-INTERPRETER::.APPLY. 2)
  21     30   0.9     70   2.0   2734  78.1        -  SB-ALIEN-INTERNALS:COMPUTE-EXTRACT-LAMBDA
  22     29   0.8     29   0.8   2763  78.9        -  LOGBITP
  23     27   0.8     27   0.8   2790  79.7        -  (LABELS SB-KERNEL::CHECK :IN SB-KERNEL::NUMERIC-UNION-TYPEP)
  24     26   0.7     97   2.8   2816  80.5        -  SB-ALIEN-INTERNALS:COMPUTE-NATURALIZE-LAMBDA
  25     24   0.7     24   0.7   2840  81.1        -  SB-KERNEL:%%TYPEP
  26     23   0.7     23   0.7   2863  81.8        -  SB-ALIEN::ALIEN-TYPE-CLASS-ID
  27     21   0.6     21   0.6   2884  82.4        -  SB-IMPL::PACKED-INFO-VALUE-INDEX
  28     18   0.5     58   1.7   2902  82.9        -  SB-ALIEN-INTERNALS:COMPUTE-DEPORT-LAMBDA
  29     18   0.5     18   0.5   2920  83.4        -  (LABELS SB-INTERPRETER::LET*-BIND :IN SB-INTERPRETER::APPLY-LAMBDA)
  30     17   0.5    662  18.9   2937  83.9        -  NATURALIZE
  31     17   0.5     36   1.0   2954  84.4        -  SB-ALIEN::INTEGER-EXTRACT-GEN-METHOD
  32     16   0.5     20   0.6   2970  84.9        -  (SB-INTERPRETER::FAST-GLOBAL-CALL 3)
  33     15   0.4     31   0.9   2985  85.3        -  SB-VM::INTEGER-NATURALIZE-GEN-METHOD
  34     15   0.4     15   0.4   3000  85.7        -  SB-INTERPRETER::%CONST
  35     14   0.4     14   0.4   3014  86.1        -  foreign function pre_search_for_small_space
  36     14   0.4     14   0.4   3028  86.5        -  SB-SYS:SYSTEM-AREA-POINTER-P
  37     12   0.3     38   1.1   3040  86.9        -  SB-ALIEN::ROOT-DEPOSIT-GEN-METHOD
  38     12   0.3     12   0.3   3052  87.2        -  (FLET SB-INTERPRETER::LOCAL-DISPATCH :IN "SYS:SRC;INTERPRETER;SPECIAL-FORMS.LISP")
  39     11   0.3    262   7.5   3063  87.5        -  DEPORT-ALLOC
  40     11   0.3     39   1.1   3074  87.8        -  SB-INTERPRETER::SYMEVAL
  41     11   0.3     11   0.3   3085  88.1        -  SB-ALIEN::ALIEN-INTEGER->SAP-REF-FUN
  42     10   0.3     71   2.0   3095  88.4        -  SB-INTERPRETER::2-ARG-/
  43     10   0.3     59   1.7   3105  88.7        -  DEREF
  44     10   0.3     10   0.3   3115  89.0        -  SB-INTERPRETER::GET-VAR
  45      9   0.3     49   1.4   3124  89.3        -  foreign function try_allocate_small_from_pages
  46      9   0.3     29   0.8   3133  89.5        -  SB-IMPL::GET-INFO-VALUE
  47      9   0.3      9   0.3   3142  89.8        -  SB-INTERPRETER::GET-VAR
  48      8   0.2    431  12.3   3150  90.0        -  DEPORT
  49      8   0.2    114   3.3   3158  90.2        -  foreign function lisp_alloc
  50      8   0.2      8   0.2   3166  90.5        -  (SB-VM::OPTIMIZED-DATA-VECTOR-REF (UNSIGNED-BYTE 8))
  51      8   0.2      8   0.2   3174  90.7        -  SB-INTERPRETER::GET-VAR
  52      7   0.2     48   1.4   3181  90.9        -  SB-ALIEN-INTERNALS:ALIGN-OFFSET
  53      7   0.2     43   1.2   3188  91.1        -  SB-ALIEN-INTERNALS:%SET-DEREF
  54      7   0.2     24   0.7   3195  91.3        -  SB-ALIEN-INTERNALS:COMPUTE-DEPORT-ALLOC-LAMBDA
  55      7   0.2      7   0.2   3202  91.5        -  (LABELS SB-KERNEL::RECURSE :IN SB-KERNEL:%%TYPEP)
  56      6   0.2    981  28.0   3208  91.7        -  %ALIEN-VALUE
  57      6   0.2     93   2.7   3214  91.8        -  ALLOC-TRAMP
  58      6   0.2     16   0.5   3220  92.0        -  COMPUTE-LISP-REP-TYPE
  59      6   0.2      6   0.2   3226  92.2        -  SB-KERNEL:TWO-ARG-/
  60      6   0.2      6   0.2   3232  92.3        -  EQUAL
  61      6   0.2      6   0.2   3238  92.5        -  SB-KERNEL::NUMERIC-UNION-TYPEP
  62      6   0.2      6   0.2   3244  92.7        -  SB-ALIEN::INTEGER-DEPORT-GEN-METHOD
  63      6   0.2      6   0.2   3250  92.9        -  SB-SYS:SAP-REF-8
  64      5   0.1   2327  66.5   3255  93.0        -  (SETF %ALIEN-VALUE)
  65      5   0.1      7   0.2   3260  93.1        -  LOGAND
  66      5   0.1      5   0.1   3265  93.3        -  ASH
  67      5   0.1      5   0.1   3270  93.4        -  SB-KERNEL:TWO-ARG-AND
  68      5   0.1      5   0.1   3275  93.6        -  (SETF SB-SYS:SAP-REF-8)
  69      5   0.1      5   0.1   3280  93.7        -  SB-INTERPRETER::GET-VAR
  70      5   0.1      5   0.1   3285  93.9        -  foreign function alloc
  71      5   0.1      5   0.1   3290  94.0        -  SB-KERNEL:VECTOR-HAIRY-DATA-VECTOR-REF/CHECK-BOUNDS
  72      4   0.1   3489  99.7   3294  94.1        -  PROGN
  73      4   0.1     25   0.7   3298  94.2        -  SB-SPROF::UNAVAILABLE-FRAMES
  74      4   0.1      4   0.1   3302  94.3        -  GENERIC->
  75      4   0.1      4   0.1   3306  94.5        -  SB-INTERPRETER::GET-VAR
  76      3   0.1   2390  68.3   3309  94.5        -  SETFA
  77      3   0.1   1048  29.9   3312  94.6        -  CLONE-OCTETS-FROM-ALIEN
  78      3   0.1    114   3.3   3315  94.7        -  SYS-LIST-ALLOC-TRAMP
  79      3   0.1     21   0.6   3318  94.8        -  foreign function listify_rest_arg
  80      3   0.1      3   0.1   3321  94.9        -  foreign function pthread_mutex_lock
  81      3   0.1      3   0.1   3324  95.0        -  SB-KERNEL:TWO-ARG->=
  82      2   0.1      6   0.2   3326  95.0        -  foreign function _ZN7rocksdb18WriteBatchInternal7IterateEPKNS_10WriteBatchEPNS1_7HandlerEmm
  83      2   0.1      5   0.1   3328  95.1        -  SB-ALIEN::INTEGER-LISP-REP-METHOD
  84      2   0.1      2   0.1   3330  95.1        -  foreign function __mprotect
  85      2   0.1      2   0.1   3332  95.2        -  foreign function _ZTHN7rocksdb12perf_contextE
  86      2   0.1      2   0.1   3334  95.3        -  foreign function _ZN7rocksdb6StatusaSERKS0_
  87      2   0.1      2   0.1   3336  95.3        -  GENERIC-=
  88      1   0.0   3486  99.6   3337  95.3        -  SB-INTERPRETER::EVAL-TAGBODY
  89      1   0.0   3486  99.6   3338  95.4        -  SB-INTERPRETER::LET/SPEC
  90      1   0.0   2352  67.2   3339  95.4        -  RDB::PUT-KV-RAW
  91      1   0.0     22   0.6   3340  95.4        -  foreign function rocksdb_put
  92      1   0.0      8   0.2   3341  95.5        -  foreign function _ZN7rocksdb6DBImpl15WriteGroupToWALERKNS_11WriteThread10WriteGroupEPNS_3log6WriterEPmbbmRNS0_17WalFileNumberSizeE
  93      1   0.0      7   0.2   3342  95.5        -  foreign function rocksdb_get
  94      1   0.0      4   0.1   3343  95.5        -  foreign function _ZN7rocksdb6DBImpl7GetImplERKNS_11ReadOptionsERKNS_5SliceERNS0_14GetImplOptionsE
  95      1   0.0      3   0.1   3344  95.5        -  foreign function _ZN7rocksdb8MemTable3GetERKNS_9LookupKeyEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_19PinnableWideColumnsESA_PNS_6StatusEPNS_12MergeContextEPmSH_RKNS_11ReadOptionsEbPNS_12ReadCallbackEPbb
  96      1   0.0      3   0.1   3345  95.6        -  foreign function _ZN7rocksdb18WritableFileWriter5FlushERKNS_9IOOptionsE
  97      1   0.0      2   0.1   3346  95.6        -  foreign function _ZN7rocksdb18WritableFileWriter6AppendERKNS_9IOOptionsERKNS_5SliceEj
  98      1   0.0      2   0.1   3347  95.6        -  foreign function _ZN7rocksdb8MemTable3AddEmNS_9ValueTypeERKNS_5SliceES4_PKNS_18ProtectionInfoKVOSImEEbPNS_23MemTablePostProcessInfoEPPv
  99      1   0.0      1   0.0   3348  95.7        -  foreign function syscall
 100      1   0.0      1   0.0   3349  95.7        -  SB-KERNEL:%MAKE-ARRAY
 101      1   0.0      1   0.0   3350  95.7        -  GENERIC-*
 102      1   0.0      1   0.0   3351  95.7        -  SB-IMPL::GET3
 103      1   0.0      1   0.0   3352  95.8        -  foreign function alloc_list
 104      1   0.0      1   0.0   3353  95.8        -  foreign function _ZN7rocksdb6crc32c13Crc32cCombineEjjm
 105      1   0.0      1   0.0   3354  95.8        -  GENERIC--
 106      1   0.0      1   0.0   3355  95.9        -  foreign function _ZN7rocksdb14LocalSavePoint6commitEv
 107      1   0.0      1   0.0   3356  95.9        -  TAIL-CALL-VARIABLE
 108      1   0.0      1   0.0   3357  95.9        -  (SB-PCL::FAST-METHOD SAP (RDB))
 109      1   0.0      1   0.0   3358  95.9        -  foreign function _ZN7rocksdb13PerfStepTimer4StopEv
 110      1   0.0      1   0.0   3359  96.0        -  foreign function __tls_get_addr
 111      1   0.0      1   0.0   3360  96.0        -  (FLET "CLEANUP-FUN-1" :IN RDB::GET-KV-RAW)
 112      1   0.0      1   0.0   3361  96.0        -  SB-ALIEN::ROOT-DEPORT-ALLOC-GEN-METHOD
 113      1   0.0      1   0.0   3362  96.1        -  SB-IMPL::%OUTPUT-INTEGER-IN-BASE
 114      1   0.0      1   0.0   3363  96.1        -  foreign function _ZN7rocksdb18WriteBatchInternal5CountEPKNS_10WriteBatchE
 115      1   0.0      1   0.0   3364  96.1        -  foreign function _ZNK7rocksdb10WriteBatch14VerifyChecksumEv
 116      0   0.0   3486  99.6   3364  96.1        -  (FLET SB-UNIX::BODY :IN SB-THREAD::RUN)
 117      0   0.0   3486  99.6   3364  96.1        -  (FLET "WITHOUT-INTERRUPTS-BODY-" :IN SB-THREAD::RUN)
 118      0   0.0   3486  99.6   3364  96.1        -  SB-THREAD::RUN
 119      0   0.0   3486  99.6   3364  96.1        -  foreign function call_into_lisp_
 120      0   0.0   3486  99.6   3364  96.1        -  foreign function funcall1
 121      0   0.0   3486  99.6   3364  96.1        -  foreign function new_thread_trampoline
 122      0   0.0   3485  99.6   3364  96.1        -  MULTIPLE-VALUE-CALL
 123      0   0.0   3485  99.6   3364  96.1        -  SB-INTERPRETER::SET-VAR
 124      0   0.0   3485  99.6   3364  96.1        -  UNWIND-PROTECT
 125      0   0.0   3485  99.6   3364  96.1        -  MULTIPLE-VALUE-PROG1
 126      0   0.0   3485  99.6   3364  96.1        -  RETURN-FROM
 127      0   0.0   3485  99.6   3364  96.1        -  BLOCK
 128      0   0.0   3485  99.6   3364  96.1        -  (LAMBDA NIL :IN SWANK:EVAL-AND-GRAB-OUTPUT)
 129      0   0.0   3485  99.6   3364  96.1        -  SWANK::CALL-WITH-RETRY-RESTART
 130      0   0.0   3485  99.6   3364  96.1        -  SWANK::CALL-WITH-BUFFER-SYNTAX
 131      0   0.0   3485  99.6   3364  96.1        -  SB-INT:EVAL-IN-LEXENV
 132      0   0.0   3485  99.6   3364  96.1        -  EVAL
 133      0   0.0   3485  99.6   3364  96.1        -  SWANK:EVAL-FOR-EMACS
 134      0   0.0   3485  99.6   3364  96.1        -  SWANK/SBCL::CALL-WITH-BREAK-HOOK
 135      0   0.0   3485  99.6   3364  96.1        -  (FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/ellis/comp/core/slime/backend/sbcl.lisp")
 136      0   0.0   3485  99.6   3364  96.1        -  SWANK::CALL-WITH-BINDINGS
 137      0   0.0   3485  99.6   3364  96.1        -  (LAMBDA NIL :IN SWANK::SPAWN-WORKER-THREAD)
 138      0   0.0   1125  32.1   3364  96.1        -  RDB::GET-KV-RAW
 139      0   0.0     21   0.6   3364  96.1        -  foreign function _ZN7rocksdb2DB3PutERKNS_12WriteOptionsEPNS_18ColumnFamilyHandleERKNS_5SliceES8_
 140      0   0.0     21   0.6   3364  96.1        -  foreign function _ZN7rocksdb6DBImpl3PutERKNS_12WriteOptionsEPNS_18ColumnFamilyHandleERKNS_5SliceES8_
 141      0   0.0     21   0.6   3364  96.1        -  foreign function _ZN7rocksdb2DB3PutERKNS_12WriteOptionsERKNS_5SliceES6_
 142      0   0.0     20   0.6   3364  96.1        -  LISTIFY-&REST
 143      0   0.0     18   0.5   3364  96.1        -  foreign function _ZN7rocksdb6DBImpl5WriteERKNS_12WriteOptionsEPNS_10WriteBatchE
 144      0   0.0     15   0.4   3364  96.1        -  foreign function _ZN7rocksdb6DBImpl9WriteImplERKNS_12WriteOptionsEPNS_10WriteBatchEPNS_13WriteCallbackEPNS_17UserWriteCallbackEPmmbSA_mPNS_18PreReleaseCallbackEPNS_20PostMemTableCallbackESt10shared_ptrINS_19WriteBatchWithIndexEES5_bPKNS0_22DeferredPutEntityBatchE
 145      0   0.0     13   0.4   3364  96.1        -  LIST-ALLOC-TRAMP
 146      0   0.0      7   0.2   3364  96.1        -  foreign function _ZN7rocksdb6DBImpl10WriteToWALERKNS_10WriteBatchERKNS_12WriteOptionsEPNS_3log6WriterEPmSA_RNS0_17WalFileNumberSizeEm
 147      0   0.0      6   0.2   3364  96.1        -  foreign function _ZNK7rocksdb10WriteBatch7IterateEPNS0_7HandlerE
 148      0   0.0      6   0.2   3364  96.1        -  foreign function _ZN7rocksdb18WriteBatchInternal10InsertIntoERNS_11WriteThread10WriteGroupEmPNS_21ColumnFamilyMemTablesEPNS_14FlushSchedulerEPNS_20TrimHistorySchedulerEbmPNS_2DBEbb
 149      0   0.0      6   0.2   3364  96.1        -  foreign function _ZN7rocksdb3log6Writer9AddRecordERKNS_12WriteOptionsERKNS_5SliceERKm
 150      0   0.0      5   0.1   3364  96.1        -  foreign function _ZN7rocksdb6DBImpl7GetImplERKNS_11ReadOptionsEPNS_18ColumnFamilyHandleERKNS_5SliceEPNS_13PinnableSliceEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
 151      0   0.0      5   0.1   3364  96.1        -  foreign function _ZN7rocksdb6DBImpl3GetERKNS_11ReadOptionsEPNS_18ColumnFamilyHandleERKNS_5SliceEPNS_13PinnableSliceEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
 152      0   0.0      4   0.1   3364  96.1        -  foreign function _Znwm
 153      0   0.0      3   0.1   3364  96.1        -  foreign function _ZN7rocksdb3log6Writer18EmitPhysicalRecordERKNS_12WriteOptionsENS0_10RecordTypeEPKcm
 154      0   0.0      3   0.1   3364  96.1        -  foreign function _ZN7rocksdb10WriteBatch3PutEPNS_18ColumnFamilyHandleERKNS_5SliceES5_
 155      0   0.0      2   0.1   3364  96.1        -  foreign function rocksdb_writeoptions_create
 156      0   0.0      2   0.1   3364  96.1        -  foreign function _ZN7rocksdb8MemTable12GetFromTableERKNS_9LookupKeyEmbPNS_12ReadCallbackEPbPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_19PinnableWideColumnsESD_PNS_6StatusEPNS_12MergeContextEPmS6_S6_
 157      0   0.0      2   0.1   3364  96.1        -  (SB-PCL::FAST-METHOD GET-VAL (RDB-DATABASE T))
 158      0   0.0      2   0.1   3364  96.1        -  foreign function __write
 159      0   0.0      2   0.1   3364  96.1        -  foreign function _ZN7rocksdb17PosixWritableFile6AppendERKNS_5SliceERKNS_9IOOptionsEPNS_14IODebugContextE
 160      0   0.0      2   0.1   3364  96.1        -  foreign function _ZN7rocksdb18WritableFileWriter13WriteBufferedERKNS_9IOOptionsEPKcm
 161      0   0.0      1   0.0   3364  96.1        -  (FLET SB-UNIX::BODY :IN SB-THREAD::FUTEX-WAIT)
 162      0   0.0      1   0.0   3364  96.1        -  (FLET "WITHOUT-INTERRUPTS-BODY-" :IN SB-THREAD::%CONDITION-WAIT)
 163      0   0.0      1   0.0   3364  96.1        -  SB-THREAD::%CONDITION-WAIT
 164      0   0.0      1   0.0   3364  96.1        -  Unknown fn 164720
 165      0   0.0      1   0.0   3364  96.1        -  Unknown fn 131904
 166      0   0.0      1   0.0   3364  96.1        -  GET-EXTERNAL-FORMAT
 167      0   0.0      1   0.0   3364  96.1        -  SB-INT:GET-EXTERNAL-FORMAT-OR-LOSE
 168      0   0.0      1   0.0   3364  96.1        -  STRING-TO-OCTETS
 169      0   0.0      1   0.0   3364  96.1        -  foreign function _ZN7rocksdb18WriteBatchInternal3PutEPNS_10WriteBatchEjRKNS_5SliceES5_
 170      0   0.0      1   0.0   3364  96.1        -  foreign function _ZNK7rocksdb8MemTable13KeyComparatorclEPKcRKNS_5SliceE
 171      0   0.0      1   0.0   3364  96.1        -  foreign function _ZNK7rocksdb14InlineSkipListIRKNS_11MemTableRep13KeyComparatorEE18FindGreaterOrEqualEPKcPPNS5_4NodeEbbRKSt8functionIFNS_6StatusES7_bEE
 172      0   0.0      1   0.0   3364  96.1        -  foreign function rocksdb_readoptions_create
 173      0   0.0      1   0.0   3364  96.1        -  (FLET SB-IMPL::%SYMBOL-NAMEIFY :IN "SYS:SRC;CODE;SYMBOL.LISP")
 174      0   0.0      1   0.0   3364  96.1        -  GENSYM
 175      0   0.0      1   0.0   3364  96.1        -  (EVAL STRING)
 176      0   0.0      1   0.0   3364  96.1        -  (SB-INTERPRETER::GLOBAL-CALL 1)
 177      0   0.0      1   0.0   3364  96.1        -  foreign function fallocate
 178      0   0.0      1   0.0   3364  96.1        -  foreign function _ZN7rocksdb17PosixWritableFile8AllocateEmmRKNS_9IOOptionsEPNS_14IODebugContextE
 179      0   0.0      1   0.0   3364  96.1        -  foreign function _ZN7rocksdb14FSWritableFile12PrepareWriteEmmRKNS_9IOOptionsEPNS_14IODebugContextE
------------------------------------------------------------------------
        136   3.9                                     elsewhere
#+end_example
* Profile
:PROPERTIES:
:ID:       3f22e967-3d05-466f-aa31-a0a88275cb86
:CREATED:  <2026-05-19 Tue 22:00>
:END:
#+begin_src lisp :package rdb :results none
(defmacro profile-rdb-functions ()
  `(sb-profile:profile 
    ,@(remove-if-not 'fboundp 
                     (remove-if 'macro-function (std:package-symbols :rdb)))))

(profile-rdb-functions)
#+end_src

#+begin_src lisp :results output
(let ((*trace-output* *standard-output*))
  (sb-profile:report :print-no-call-list nil))
#+end_src

#+RESULTS:
#+begin_example
  seconds  |     gc     | consed | calls |  sec/call  |  name  
----------------------------------------------------
     0.000 |      0.000 |      0 |     2 |   0.000085 | PUSH-SAP*
     0.000 |      0.000 |      0 |    17 |   0.000003 | SORT
     0.000 |      0.000 | 32,768 |    16 |   0.000001 | EA
     0.000 |      0.000 |      0 |     8 |   0.000000 | PUSH-SAP
     0.000 |      0.000 |      0 |     2 |   0.000000 | ROCKSDB:ROCKSDB-OPTIONS-SET-CREATE-MISSING-COLUMN-FAMILIES
     0.000 |      0.000 |      0 |     2 |   0.000000 | ROCKSDB:ROCKSDB-OPTIONS-SET-COMPRESSION
     0.000 |      0.000 |      0 |     1 |   0.000000 | ROCKSDB:ROCKSDB-COMPRESSION-TYPE
     0.000 |      0.000 |      0 |     2 |   0.000000 | ROCKSDB:ROCKSDB-OPTIONS-SET-CREATE-IF-MISSING
     0.000 |      0.000 |      0 |     2 |   0.000000 | ROCKSDB:ROCKSDB-OPTIONS-SET-PARALLELISM
     0.000 |      0.000 |      0 |     1 |   0.000000 | MAKE-RDB-OPTS
     0.000 |      0.000 |      0 |     1 |   0.000000 | DEFAULT-RDB-OPTS
     0.000 |      0.000 |      0 |     1 |   0.000000 | PUSH-OPTS
     0.000 |      0.000 |      0 |     1 |   0.000000 | MAKE-RDB
----------------------------------------------------
     0.000 |      0.000 | 32,768 |    56 |            | Total

estimated total profiling overhead: 0.00 seconds
overhead estimation parameters:
  6.7520003e-9s/call, 2.064846e-6s total profiling, 9.92704e-7s internal profiling
#+end_example
* Graph DB
:PROPERTIES:
:ID:       e774026d-a8ed-4cfb-8190-29d09f08bf4c
:CREATED:  <2026-05-19 Tue 22:13>
:END:
#+begin_src lisp :package rdb/playground
(init :org-graph)
(org-graph-stats)
#+end_src

#+RESULTS:
| :NODE-COUNT | 2102 | :EDGE-COUNT | 2104 | :FILE-COUNT | 154 |

#+begin_src lisp :package rdb/playground
(init :org-graph-db)
#+end_src

#+RESULTS:
: (#<RDB-DATABASE {123B827A53}> #P"/home/ellis/.store/db/graph/"
:  #<ORG-GRAPH-SCHEMA :fields (file title hash atime mtime node edge node-tags
:                              node-links node-properties node-priority
:                              node-schedule node-file node-pos node-state)>)

#+begin_src lisp :package rdb/playground :results list value
(organ/db::og-values "file")
#+end_src

#+RESULTS:
- /home/ellis/comp/org/graph/app/cas.org
  5B37C685-AB0A-4D3B-B278-C99F90292FCB
  88D59A87-DA3B-4121-AA3C-541211F304A7
- /home/ellis/comp/org/graph/app/desktop.org
  CABD6581-92DB-4E5E-B9CD-F5A1C09A8145
  4B669611-0283-4A6C-ACFD-942868D5BEE3
  D6D7338A-E161-45B0-BCF9-E50FEF6D9B86
  4F39C714-4A7B-4CD3-89A2-0C0C7B0953B9
  9B98C316-303E-4919-8A7C-09965FFF6C17
  B8588986-EC59-41D1-91A4-901E3C7217D3
  66CBBDAC-801F-4C42-B16A-09CDE9A69A7F
  CB4981E6-AF47-400E-A761-4A73B3DD791E
- /home/ellis/comp/org/graph/app/emacs.org
  5FC53135-1B6C-4260-B264-66BE7A2B8FF0
  CFE9D1B9-F6F4-4866-8291-D125FC8B3EB6
  31710A0D-BD27-4549-894E-62BB8CEAA015
  21ADCC1C-67EE-4F50-9049-12794824B2C7
  2CEBD8B2-615E-44B2-AFD4-2E302F836DD3
  A42C2AAA-8DDA-40CA-B455-7511F0CB084A
  B72F96F7-4040-4548-8DA2-E619D26C4887
  DB8E43F4-78EC-4FB1-93E7-11AC7EE87799
  F499C680-9A01-4A11-BC69-81861FD864D0
  86DBF792-301B-405E-806B-3DF7E9531279
  8B1452EB-FC57-4026-8587-91FF8EBCCBA6
  92AD7518-CF81-4ACA-9940-BD40FB02F5DD
  C344FC40-D6D8-4553-885B-FE8C55D6AA98
  C40383A3-C717-43C6-8188-E2A564A641A1
  8B2930BE-E877-4E6B-AEA4-372BE3C8340C
  3BB08E71-1CE9-46ED-844A-31305162645E
  947597C2-8F17-4BA8-8AF7-6D5784219B0C
  B1C1D365-1983-4E63-8CF6-C032932FF1B9
  371FF3E8-D0E0-4260-BC41-4BA53D635CE5
  C69F7D77-7EC1-4D7E-B70D-23E54CDCED4B
  5FF7407E-32A0-463B-BF59-9519875DA655
  1BBC8529-D207-4A7E-A72A-B231316C90E6
  DEFA663E-3522-475C-AD44-615B64EDABF1
  4D72736E-F3C1-4B6F-839D-474710771D78
  CF98496A-D864-4878-8401-FFAA73AA7D04
  C6D79F1D-E5BD-479E-82FA-20DF7E5DD83F
- /home/ellis/comp/org/graph/app/gnu-radio.org
  C92B3830-3836-41B0-A502-F04B44CD3292
  C272A3F2-B0B0-4784-AEAF-4C677CBBD708
- /home/ellis/comp/org/graph/app/gnu.org
  5FC53135-1B6C-4260-B264-66BE7A2B8FF0
  CFE9D1B9-F6F4-4866-8291-D125FC8B3EB6
  31710A0D-BD27-4549-894E-62BB8CEAA015
  21ADCC1C-67EE-4F50-9049-12794824B2C7
  2CEBD8B2-615E-44B2-AFD4-2E302F836DD3
  A42C2AAA-8DDA-40CA-B455-7511F0CB084A
  B72F96F7-4040-4548-8DA2-E619D26C4887
  DB8E43F4-78EC-4FB1-93E7-11AC7EE87799
  F499C680-9A01-4A11-BC69-81861FD864D0
  86DBF792-301B-405E-806B-3DF7E9531279
  8B1452EB-FC57-4026-8587-91FF8EBCCBA6
  92AD7518-CF81-4ACA-9940-BD40FB02F5DD
  C344FC40-D6D8-4553-885B-FE8C55D6AA98
  C40383A3-C717-43C6-8188-E2A564A641A1
  8B2930BE-E877-4E6B-AEA4-372BE3C8340C
  3BB08E71-1CE9-46ED-844A-31305162645E
  947597C2-8F17-4BA8-8AF7-6D5784219B0C
  B1C1D365-1983-4E63-8CF6-C032932FF1B9
  371FF3E8-D0E0-4260-BC41-4BA53D635CE5
  C69F7D77-7EC1-4D7E-B70D-23E54CDCED4B
  5FF7407E-32A0-463B-BF59-9519875DA655
  1BBC8529-D207-4A7E-A72A-B231316C90E6
  DEFA663E-3522-475C-AD44-615B64EDABF1
  4D72736E-F3C1-4B6F-839D-474710771D78
  CF98496A-D864-4878-8401-FFAA73AA7D04
  C6D79F1D-E5BD-479E-82FA-20DF7E5DD83F
  C92B3830-3836-41B0-A502-F04B44CD3292
  C272A3F2-B0B0-4784-AEAF-4C677CBBD708
  0B60EEDF-686B-4F9A-BC2B-7CEE2BE7E828
- /home/ellis/comp/org/graph/app/heptapod.org
  C2B38CD6-ED93-49AF-A3AD-D27D270DA58D
- /home/ellis/comp/org/graph/app/mail.org
  BAD99155-7F62-404C-AE48-18D753BCDFB4
  E95CEEDD-8AA4-4084-BC32-2B91D1FD4F24
- /home/ellis/comp/org/graph/app/media.org
  9DF7A344-14A4-4D14-939A-B59894D7E676
  97FF5B91-CF31-4FDB-B563-C24E08C5CD24
  349E75DF-C3E3-4C1D-90E0-161E014ECAFF
  DCE6EEE4-1B5E-46B0-BC16-36803E3CA410
  62DD0033-F7D3-47BA-A42A-B48A7BBBC11A
  3364B5D7-D09C-4CBA-97CF-0FB3D08A8E03
  C2070931-D7B2-4967-8839-A34FC07B740F
  010BA610-1FCF-4D48-B030-35FA82FBF0AC
  93DDB271-71B9-4E93-94F9-1EB421988F33
  C0A50A82-A1BB-4DC6-A0F8-6191701AE69E
  0C1B92BE-522E-43BC-A00D-C54E762DD399
  D52E885A-CE1F-48B4-A111-73C04DCF7D3D
  2DB1BE6B-196A-4BA4-BA3D-C3440D314762
  A24E5FAC-1D67-4A47-99B6-C7AEFA11644C
  0DF3A71A-F52B-4789-AE0C-EAD38FB5CA35
- /home/ellis/comp/org/graph/app/net.org
  54B782AE-11C2-4546-A506-003A21FD9537
  49A90B67-054A-4591-B73F-8821DBA7C060
  51CB270E-5C5A-4605-9867-AA40A68DDCEB
  DE59CC69-D16C-4FF9-87F4-1D95F34525E9
  0290F01C-13AB-4268-B9DE-030FFDA5A4B8
  CAE8DE41-BEB8-42B3-BEC8-20F0A29DD59C
  FDAE8DCF-92F8-4A72-B91A-8A830E80C17B
  74E5DB7A-BB98-4A54-A7E6-FAB58F580ACF
  F7A60F4C-2AA4-4330-95BB-7077AB534258
  2415D486-E74B-4318-90CC-8D68C4BFFB2E
  A6291723-D71E-4E1F-B53D-ED5914551E80
  E0D6567F-73E8-4A02-8360-4938D7994F3A
  163FACC3-2D47-47EE-B0C8-0512A3EFCD13
- /home/ellis/comp/org/graph/app/package-manager.org
  26B32AE2-B49C-42CB-A0D7-4823221B79F2
  0A40D25F-0FE5-4B71-9D22-07D4BB355FF4
  836933B5-3035-4E8C-A2B9-63A773A359DB
  3C814D4D-8635-4C6F-A849-5C7D72DB20FE
  05CC62C7-DB2A-4BF6-B94D-E04A2B17AED0
  219F8BB6-B324-4A33-87E0-69114948C0F6
  B52FDC61-2FCC-42E0-A1DF-66EBD0CA0488
  8907D7FD-AE27-4A36-B7F0-3B3A8E6745C9
- /home/ellis/comp/org/graph/app/pm.org
  8907D7FD-AE27-4A36-B7F0-3B3A8E6745C9
  E8358B3C-E658-40F8-920A-40F5692F910A
  7D1A905E-A311-4680-97AA-2BBFD939E5E7
- /home/ellis/comp/org/graph/app/podman.org
  89199DCD-FABD-4952-B5E9-1B3FFAF06E6B
  3EFD02F4-B340-4566-A7FC-95B3C895C762
- /home/ellis/comp/org/graph/app/qemu.org
  C4F26EF4-A936-4CF3-8218-4D23DBD9B33A
  C2B1211C-870C-451D-B0FA-F9CCE4F6A0A7
- /home/ellis/comp/org/graph/app/term.org
  A1BC7F75-4B67-452D-9C30-54420F66E1C5
  B6CC9844-E152-4227-820D-D7D00C7381AA
  8C91F0E4-8CC5-4622-8E34-0F0EAB0818AE
  391C9F4D-BEAD-4F9C-B946-0E2D191AA94B
  528D0B97-B753-40B1-8DB2-198CE59296A6
  3C83B6E7-FA30-4E48-88B2-5D96E749E60A
  CF221F30-3844-4B94-8E73-B8BDEB80F8DB
- /home/ellis/comp/org/graph/app/vi.org
  17D03ADA-139B-4127-8865-DF1B5B50EABA
  DF400751-0B3E-41A5-8512-A778A58CC1BD
  A92FCC96-FBF4-4F02-A2BF-0E2676D0EF7F
- /home/ellis/comp/org/graph/comp/ecl.org
  03934099-5CCA-488C-AA5B-ED5DD4BFB428
- /home/ellis/comp/org/graph/comp/gcc.org
  B3639401-B960-42D3-8325-7B5E056E3478
  7F1C6B41-A71D-46AC-B48E-E45EC3F44DB9
  4B5E18BD-CB9B-4F83-A463-E4A95764104B
  2A3947B0-A120-4C48-A8D5-F9C01DEB49B9
  F6074A9E-0C44-4DD7-A472-DFAE30CE34DB
  AD2E3567-2C78-40F5-9A5D-2FFB66E5FAE2
- /home/ellis/comp/org/graph/comp/ghc.org
  9A00B903-EA15-48D3-8440-025998CA857B
- /home/ellis/comp/org/graph/comp/llvm.org
  496B952F-4C98-4303-92B4-1C766565092C
  05EEED21-6ED4-447D-8C8F-DAEE2DD112BF
  3F0ED70C-6774-499C-9C15-A28A5E653161
  F283DB5A-BBE5-477F-834F-46B9AC992BAF
  339518E9-2112-4C79-9471-CCC8F57B8105
- /home/ellis/comp/org/graph/comp/sbcl.org
  A7F9B428-9323-492F-AAA5-94669BFBC55B
  868E5534-1AB9-49AA-88C8-F9529B3DFC98
  11329FDB-2923-4CCF-953C-037E78433B1A
  E99F0D2A-546A-479E-9014-3ACDBCCCD5AB
  DC91FB4A-ADEE-44EC-9BD8-CBFA10DB8DCA
  6FF7096F-A666-4103-8F32-1DC62C04CB35
  7BF0993F-6212-4635-A071-BF2E7D9BA7F9
  BB27D9C3-513A-4AC6-8780-580C09257040
  660A290F-E3D8-4568-B431-104A9E79956C
  5A3DEBD1-9B38-48F0-BBCD-8CF3F18E8407
  C33D77C8-188C-4BA0-90FF-F49FAC6468C2
  9AAC997A-5D9C-43DD-B2CA-8B8B02D9F2DD
  FE6F9AAC-D7C6-497E-9EBC-A284C67466A0
  D3503F8E-EEBB-4C8C-8EBE-A343DBC9E0E0
  9AA17E32-5677-4FF1-9E85-6DF91557CEA1
  ED7C8A7C-0B0F-42F5-9E68-B2528FF26AF9
  4F3868B5-131E-4D3D-9833-BBE00D0D6CDE
  7FFB42F4-37F7-43EA-A252-21D00B0D6AB7
  BC043C0E-2F31-4955-89D2-B3C4C158BF3B
  F80F9AAC-24A7-41B2-A1D1-93DC59E19083
  FD50E430-8A51-406A-96BD-AE6A1CF73BDD
  E345E677-E9E1-496F-8F58-2F77E3A44000
  57FF5711-3CB1-4602-BB74-5C6E46E152E7
  A4D05DA6-B90D-4A9F-8237-67A10C8C4588
  7AC78145-D44B-425F-B155-65057C2D0735
  CE61D665-FB20-44FB-990B-2EBDD11A038A
  39A7E730-9190-4AD1-A309-AEF4C9AF2D4A
  21D645AA-940E-454D-8F86-4DF8D9084A8C
  32E166AA-ADD7-490C-83DA-246D2CCCD011
  7CE03245-5FE3-4E8A-90B5-833FD4C53803
  2A85508C-7F32-4DCA-98E8-E89B2FFDE3FF
  618F6721-594C-42A5-8D7D-61445861E4D8
  9C11FBB6-0E98-4E46-9248-B706AE1624A1
  A8EE911D-6D19-452B-B03A-249A446C1B20
  DB473315-0C74-40CB-AB07-9259B2113043
  70679001-871E-40C6-A660-D766E355E871
  5AEA02C4-E9D4-41E2-81A1-D1BDFAEAE05F
  36FC490C-6AF2-477B-9D69-67AEC305BB26
  F66C31EB-099E-4245-AAB1-B397C1DDA900
  F9BCAC71-99B9-4375-9C23-8B650D21D86C
  93E1ED13-DC82-4A9B-8B9E-F60F06B01A4F
  4614D042-F2AE-49EA-A7D9-A29C4AED3210
  86674FE2-4105-4246-9682-F6E3FB84F7DE
  624CBC9A-9797-4889-A8B5-8440B04D9C01
  76C64438-4DB7-4318-8701-241D4F253782
  77D8F492-2707-43D5-893F-AEB14338568D
  B260F2DB-6EEC-4F79-9F4F-F6E080062442
  1F626E1C-10DF-4297-A2E7-3BDE34C4EE0F
  31CEBF6F-E67C-4289-A75E-AD012B4BBE5D
  6BECA36E-6264-4741-9180-66E81BF58C49
  C33A5587-DAAB-4E61-A0DF-FC6856B00F70
  0C2908C2-69D0-4866-B225-3D7EEC026B76
  74AB7482-7057-4BDB-A58A-C2B013583EF8
  831BC450-0723-4662-BACE-29F0E3835673
  D2269803-9084-4845-8860-047C37DA36C7
- /home/ellis/comp/org/graph/hw/amd.org
  E2368655-59E9-404B-9AC6-CECB35216C11
  ABEC3188-A2E3-4ABE-9B45-59985A6CA303
  812054ED-D108-43F5-BBA7-E40F9604C0C8
  86C29A1A-359D-4049-816D-2EC56E6BDD5F
- /home/ellis/comp/org/graph/hw/apple.org
  C5D7A7B3-09F1-4F0E-909A-63111C039CC3
- /home/ellis/comp/org/graph/hw/avr.org
  EC0316F3-DB1A-4BCD-966C-2AC0BB3458F0
- /home/ellis/comp/org/graph/hw/car.org
  E6A7DB9A-B591-48F9-AA9C-296968821599
- /home/ellis/comp/org/graph/hw/cpu.org
  20E26C76-3247-4434-89DC-CBD5712FDF67
  1B41D186-948D-4EF1-B36D-F3E2FA14FA3D
  EAC350D1-FECC-4B02-A933-ACD6121789A8
  275C4CF2-2703-4261-A3C1-49720E9A61E4
  B64AB310-F4F1-4BE7-991B-D38EF4AD686F
  CF84218A-5BBC-4B73-919B-994CBD0E2845
  08A19348-2262-4BB8-B5BB-FC2D5982553F
  C7D1E078-91A1-43F6-8269-3CE4C592DB3A
  C88D5CE8-3348-4347-B85B-15CF4EF61E4F
  F4E6553B-2E09-48B1-AC4F-A89FEFAB8BE9
- /home/ellis/comp/org/graph/hw/fpga.org
  2365BDE4-4442-4FA7-A005-2AC7AD83192A
- /home/ellis/comp/org/graph/hw/gpu.org
  05A6AE25-B2ED-4EDB-9104-E6894819B96E
- /home/ellis/comp/org/graph/hw/gsg.org
  F8B83779-83C1-47FC-88E7-C76018E4B8DF
  74F75829-FDC6-456E-B306-AB42B18260F3
- /home/ellis/comp/org/graph/hw/home.org
  E884DE4B-3762-4991-BD24-58727C28DE12
  D8F28D23-9EA5-4AEA-853B-F41884664F0E
- /home/ellis/comp/org/graph/hw/honda.org
  0CBDDE1C-8F48-40EB-B090-975CFF3FFEAE
  99C456F5-D1CC-4DE3-8C76-6B02990B8E30
  0A1A68F5-ACEE-4762-8136-477F8FE3E5AD
  F213DAB2-1CDA-47EE-88F6-6F7E7754F74E
- /home/ellis/comp/org/graph/hw/hydrabus.org
  632212EB-ACCB-4660-A46A-C8688C5D237A
- /home/ellis/comp/org/graph/hw/intel.org
  4555306B-B68C-43A9-8A54-E4066CA7437D
- /home/ellis/comp/org/graph/hw/kbd.org
  DD783D1F-3FA9-4AB2-8C6C-766375A8C725
  84FE66EC-C16D-4D4D-BDEB-90B08AD73552
- /home/ellis/comp/org/graph/hw/material.org
  A10424E7-6E2D-4F4F-A232-53359D785E00
  162F375B-E3F5-414A-BFD4-939DF34290BD
- /home/ellis/comp/org/graph/hw/nvidia.org
  EAF2ECF5-7748-40E5-BD1B-C8FC2053D050
- /home/ellis/comp/org/graph/hw/philips.org
  7C836FA5-DE1A-4075-9FF3-1FDE1A5910BB
- /home/ellis/comp/org/graph/hw/pine64.org
  5271A4AD-B01C-4F3B-AB23-24A321BB3D30
  7A6C02E7-88DB-4DE1-AD62-3A48717DFE5D
- /home/ellis/comp/org/graph/hw/samsung.org
  F67CC642-30FE-4DD9-A78D-6C5296DC861A
  978EAE63-4D8E-4DBF-BFBA-B135D82AB027
- /home/ellis/comp/org/graph/hw/shop.org
  6496205A-1DD9-4AEC-9B32-EE5A44156839
- /home/ellis/comp/org/graph/hw/sony.org
  A6A352C3-A4CC-4553-8107-BFEFDE8CDCD6
- /home/ellis/comp/org/graph/hw/storage.org
  83089757-22C3-456D-9B2C-C119ADEFD8C2
  173D1ACE-338D-4656-9CB6-39E974CE83D4
  07CA16A0-8176-4270-BAF7-8BF301CEA669
  8BBCE9F1-FBA5-4E4E-B4A8-F659D965CA59
  26D71779-E168-4836-93BC-7EA740BEED3F
  E8148B90-9924-4F5C-9A39-BBBC4EB1CA7E
  1671E1EE-864C-4165-8740-01E68D0DC942
  E2726251-7FFC-44DB-A609-FDB19729F89E
  F321298B-98B8-45F7-AEA7-C68046F5E834
- /home/ellis/comp/org/graph/hw/studio.org
  42CCF6B6-930A-416A-A7BC-7E53B1D2E8C8
  A8A508AE-1497-4000-B358-35F3C2997D37
  6F28587A-20E1-4E80-85EA-4AC0F1C1D13E
  83ECACBE-757F-407D-B90A-8111FCF677D8
  25271E2C-9741-43E9-94E0-FDC895F64D04
  C2B003F2-54B9-4EFC-AB9D-937DC2B90B2E
  8B498584-C5B9-433A-965C-047ED5A49D44
  969FF16E-1D67-4B6D-B4C6-A5FBE0C7EA15
  2CBC0EBC-361C-4BBE-940B-3C676A392A3A
  CDE93921-A7A4-4ADA-9C84-5656F5E22629
  282B432E-5FAC-44BD-9017-719166A41726
  031DD5D9-6572-46B6-A73D-A2D31D9E23B9
- /home/ellis/comp/org/graph/lang/apl.org
  EEE94CD6-7A01-4BF1-8029-F98BA665E0B4
  A77F962D-087E-4E94-97A1-570DA3E02F7F
  30DE3F47-D339-4190-AB43-793A6948E8E0
  B6C9E124-2B17-4A1F-9195-4859BAD6C351
  63B19336-6FF6-4B49-9F9F-A0C7659B0950
  02D2FEC7-4F1A-4881-8401-72510EF8C83B
  C067CD27-99C0-4E3D-804D-E9EB1F1514CE
  AE27740F-E1FC-4DAF-BD2D-D1A4BC59D193
- /home/ellis/comp/org/graph/lang/asm.org
  C57C2462-7E95-4E6B-9F5B-D7207AEDA442
  E4F61FA4-82C8-47C4-8EAF-0C6F6CD6C347
  5F4DAAA9-8536-4051-B2B3-B4669F7960EE
  2A7304BC-B666-4EA6-A37D-64487875FF4E
  3EEC30C3-AB67-42F1-B77F-191905D43C6C
  4C7530B8-6D6F-475A-B2A3-986A10A0D812
  C9748BD6-8F6B-459E-B863-B2B155E3E420
  D9641715-F038-4093-961D-87489FB2390D
  D47A1EE5-0CF8-4EA2-9D5F-4C2396F34BC8
  9E9BFA13-EED1-49A8-BAD1-BFA2F2DADE86
  37C0D23A-8C9B-49D9-98E9-964CA52BE6DE
  3234C77C-97DD-4180-B8CA-48E18DE7AB81
  C06FCD4C-193A-4BA7-BD16-3B8E537DD2AD
  96D5AF9B-48F1-4D26-BCDD-A6ED47A73141
  5C9317C4-D3FC-4648-BFE2-38D9CA0719EC
  5AABF9B2-3071-40CC-ACFB-F93ED4A15AFB
  16A8FFE9-DA94-43DD-BE0F-7E0D7AF68476
  E6C89750-0770-4C0F-A943-F6419313970E
  88F212AE-23D2-4B10-B78B-7139DBA28E64
  BB8A87BA-B251-4C9D-A829-4231547D68D8
  0325F88D-545C-4D10-BE76-F503C1AAA37C
  BDAE141E-3288-4108-B509-DDDD4A8B3731
  25754E07-2C57-4385-A52A-33B0179E2B85
  650A3FC0-6EEC-4B9C-8DB5-B89715FF50CC
- /home/ellis/comp/org/graph/lang/basic.org
  5518920E-E160-4D02-BE4F-E73E2C89AF45
- /home/ellis/comp/org/graph/lang/c.org
  5479D877-2BD1-41D9-8409-1FF0436FCC59
  0157D160-7EEB-4E01-AB69-43000E09CC3C
  9132FF22-4C85-4AED-AB5C-1BD777648927
  F9A7443A-A362-4D47-B3D3-045FDD6C3C57
  6C5A4DF9-612C-4591-BFE9-7904CC03FB4C
  93CDDD0E-4189-4E78-A0E5-B3CEAF6B7D6E
  3AA8B635-2C81-4992-8E65-FB2B0DEE7B06
  D77ECB14-ECD4-4432-AF2E-F431BF9EA18B
  1770AFE7-1224-486B-BD35-2C24BB526BA7
  E9BB191E-5226-4BFF-B2EA-94716DAC48E7
  C7E3F469-F1C9-4B9F-A104-72AE91ABAB21
  75819BF7-326D-49E1-8A4B-B93E1336B7DB
  FFB7BA79-A805-43B3-B304-0575005E19E1
  B0FF5843-38DE-4BD9-800A-728391DAFC02
  E25FD7F1-8387-4572-8CEE-F2DA0183D5E2
  7F29CA19-B76C-40C0-981C-41C4034ECF4C
  8ABF5410-165D-43C5-A37B-FB9BE29F227E
  EA07B1AC-7E78-48BE-A192-41B52A08002B
  6E354901-1B1D-43F3-B299-1FC8C67AA45A
  BE1C5802-61BD-4B32-9566-03CEF321236E
  AD099AE1-D55F-49F4-99C7-DE92CED85488
  2B62B530-80C0-4A78-828E-509AC78DBFD9
  D7C12344-B1AE-4BF2-A620-BC99F8E71E29
  F4BFDB27-161D-4B47-B417-55AC4EEFF234
  A531E912-55AB-4889-806F-475C0316713E
  3021FA48-A98A-471F-896C-DB237E97192B
- /home/ellis/comp/org/graph/lang/cobol.org
  B350B221-28ED-4866-971A-F1A4DBE4F3B4
- /home/ellis/comp/org/graph/lang/erlang.org
  609EEF50-A8D4-465C-808D-93C623C05A85
  D3EC4A82-1FF7-44BC-B34F-6E2CC66DCC84
  98BD675D-6C08-427C-ACFF-FECBD8DCB8B1
- /home/ellis/comp/org/graph/lang/forth.org
  FFB8BE57-D874-4540-9FE0-9EFEA6559185
  C8359E6E-401B-4C7A-915F-98DC2759C995
  8263AB5F-CED9-4BC6-B22C-2D1F319394EE
  3F65CFC7-F3B0-4B50-B20A-D775936AD08F
  2A285BBE-715D-49A5-8FCB-DF9921C3352B
  35DE6467-E9FC-49F4-B46B-0E05029F9F48
  B0F61B51-FBD8-4B45-A8CD-0A2E08864FED
  39AF0F8F-AFF7-40F3-A139-E1338A6BB966
- /home/ellis/comp/org/graph/lang/fortran.org
  F32A0D3A-79B7-4853-81E2-BAFD46F33428
  A005BE33-AA42-4D92-8237-0ED5D791E8E8
  F1143E94-AEB6-45CF-A072-317C3B9862C5
  449AAD9E-ABD1-4A10-A1A8-D6A1C3356542
- /home/ellis/comp/org/graph/lang/go.org
  2FC595AD-F426-4247-98FF-9B2AB5EB1ABA
  0CA9D35C-D70C-449B-9671-7F2BD5EE2705
- /home/ellis/comp/org/graph/lang/haskell.org
  917C397B-01F2-4F02-8B27-ABEEEAA463AB
- /home/ellis/comp/org/graph/lang/java.org
  99715E32-2635-4425-B2B5-A1FCB4DDB9A5
  6819FC08-3199-49BC-9C5D-B19419118525
  84A7EEA1-0059-4A07-945B-C4167CA38F26
  DAABDEC4-5708-4BFE-AD37-41469D0DFE17
- /home/ellis/comp/org/graph/lang/javascript.org
  D9226DE2-4B80-4193-A06E-E3185FFB5217
  F591261A-576F-4E4F-87C3-E19833B85EAC
  CE8B2093-0CD1-4D6F-B174-BA4C20124BB4
  1252C186-C72A-4A0E-B2D9-B325B826CEA5
  66853806-45A7-4E01-BE31-29C6F76D8F6D
  BA734E40-8FFF-43B1-A68D-3D7A1C2AFE8D
  302AB51F-539E-400E-8F59-124F1CB89676
  7DDD2D60-6A99-4948-AA7B-F36DC9839599
  FE82F0C8-B506-46B6-8384-D9439BAAD99C
  54F1F814-5B88-4F46-83AA-CD26841B1DFA
  FF42D3AA-94CF-4F88-8FE7-9F54FCAF95F6
  1DD1FF5B-C2BB-47FF-96D0-F56D2FAC465B
  5886CA2E-A096-4F08-B08E-75DA2C12109A
  9BE0CEF1-830D-4D76-970E-F786CD60D48F
  B2F13EDE-DB9D-494B-A454-515496CB6B7E
  84BD750F-75F0-4B23-B18E-7868783FDACB
  3F02FC98-932E-41DA-A810-2B8C4B31083F
  E0C38219-7B90-4981-A46F-D3FE92888996
  05A83166-2AFC-41B2-8B64-9FCB2A33A5D8
  CCBF8BB8-4195-4E6A-8A72-87A7FED916B1
  FDF7F4EE-049D-4050-AC28-501726B0E2A5
  53BA1F16-8E99-427F-8456-FCE832F57E1C
  103A7228-964B-4075-98E1-1E3CA730DC52
  F2570E7E-B15D-4E75-9AE9-A12E581CB510
  161D575A-30E7-466C-BFF8-DF5D05B21D8A
  58D76125-7110-4C76-B8D4-7014D407CC1D
- /home/ellis/comp/org/graph/lang/julia.org
  BBC7CF8A-268E-4627-8979-4438BF9786BF
- /home/ellis/comp/org/graph/lang/lisp.org
  AF0ED8BB-4B45-42F9-B8BE-82B8EA7935A3
  DF41336D-5185-4047-9644-E25925529F08
  4E502DC1-C22D-444E-B4C0-864876F0CDF5
  DB68087D-CC4C-462D-B4E0-BBDA756DC37C
  8BC4FF14-F001-4515-AC1F-FD59EF8EF506
  4E7B8135-3D53-4739-9A72-563971A5B876
  F9D8EEAD-51AB-4589-A5C2-2569EA1B7ABD
  3F613B5A-6AAE-4852-A4D8-C322C271E6EB
  6935DACA-1AD0-45B0-97E5-F59745F06AD9
  BBDC87F1-CECE-474F-905E-D02401E82510
  62417B14-EFFF-448D-92C0-5B0E99A180EE
  1535CA58-7141-4886-A1C0-90E4F29FC2C9
  D185B690-D2F8-46B9-A32D-2A95F0EE6D82
  0CDC5EB0-A12A-4276-8382-0B81F661A2A8
  681706BA-D885-46BF-93BA-C8E051C79AEB
  4D5F7613-0441-4F69-B559-24F12AE39E15
  852B2C7F-238E-480D-AD63-3B5B53C58929
  EBBC665A-10C3-46A3-8052-4F46BC9AC2B1
  7555F8C6-5DD5-4607-AE1F-32643BF03BA9
  D69C0095-59E3-4005-8360-F928C3ACE460
  439A02F1-AFCF-4BA3-BDF4-0304D152BA6F
  D9062D16-09F0-4C48-99AC-2E26407FC75B
  1CCB1FAA-6E41-4B4F-877F-4382BC250E53
  961D0C81-11F0-49E2-8CCB-9C31F6B6528D
  475491E1-EACD-4759-BE06-1C027E91F565
  54D32D4A-93FE-4F4D-9207-F291DBB1EDC6
  C57D3869-02D6-4E5D-BB09-804D18C07124
  10097B58-8A54-4CE2-84E9-FF15D4D0F5BF
  ABCD966F-FD1B-4679-B956-FC4891647668
  B34C6E3F-6559-4D7E-A554-B7B83CCC4D8C
  82D4DFFA-070C-4EAD-B317-9F9B6820E2C1
  F666C1B5-2900-44A2-85BA-2AFB029D32AB
  CC72C2C8-8A05-432E-8E7A-844EB6C9AC15
  D68D93F2-DBEB-410C-8FEE-AF71D3A4B0A0
  B93F8626-0816-4DE6-B6BD-9C796BE468E8
  54EA6883-851D-4829-8F71-889AA7F58C45
  503387D8-FA9C-4269-99BC-1D29415AB290
  1BEB282B-8C4D-4561-A293-07439D0367AE
  8AF234C8-1455-4DC8-A2DF-E6D5B5777606
  E70D50DF-D897-4A5F-A669-FA5DC3F94B23
  0FA56FD5-0B93-4B2F-BE00-8197275BB5EF
  DF045D95-A55E-4E87-A450-CF683E0EBD19
  C9515816-FC3A-4976-A5ED-138CBEC83AA9
  98B691B5-A617-438E-80EC-FB31588BCC3E
  AC5922A8-06C6-4608-8305-EC42CEEA4EE9
  20EA4FCC-E435-4738-93F3-A29572F0919B
  A911344D-AED1-4603-A46F-E8EDF53756F5
  C560DC07-8C9C-42BC-9CE1-634630D26981
  C42732CE-9EF1-408B-A9DD-2424D05DE398
  3ADDEE17-B990-4A6D-9767-071969ED9D0E
  B8D8538C-7BE9-4271-BF8E-897E9BA5B6AD
  0AA28DD2-D424-4021-A775-095439DFFD7A
  26CD6032-0E6E-4F9B-AE9F-2B88AA95DAFC
  A69E0D55-E25F-4332-8FDC-AAD2843BA649
  894CE499-1CE7-4051-A921-661995FE42B2
  A6911466-C135-488C-A67E-689F22592A44
  FB68413A-ACD8-4107-BFB5-48CE32BE8842
  2A62E513-65A6-49F0-9965-D25710186BC3
  92DD3F0E-4789-4016-A623-48AF3C45CD05
  7F63F416-EFCB-4926-8370-B626C4349C45
  D0796FFF-4A90-42A5-8213-93E2CB5C9465
  FB444369-A3E2-4451-8AFC-E29571E706DE
  3951AC2E-DC3D-4C25-B0AB-7B1DAAC53B47
  377A92DD-8E6E-4183-BD8A-70C47902D4D8
  F8F4D3EA-663A-4A8E-A9A8-F0D7813C710F
  04D98054-94F2-47D1-8AF4-751C10827EE8
  91C00D39-6541-4B29-8D6B-A5B8C770CAB0
  53D96196-24D4-4737-93D0-A282F2CF5C0B
  11B9F51E-4D47-41BA-814F-AA6738A65881
  2B73B4E2-495A-4AF0-9777-294196AD7F4D
  D41019FD-CA88-4608-AF00-9E7A84DCD49F
  E310D8EC-2A13-4A8E-AA15-DB29738656B9
  6027AA9F-E3F6-4CF8-8C20-CAEF166A5126
  1F1A5A5D-DE86-461F-A209-9D81298D9A7C
  0B568DBE-FC89-4CE6-BE86-FD18D1D2D5C0
  6CFCA9D2-8D3D-4725-A08F-349E08FD44E3
  CCE00DB3-1428-4380-AA5D-8D2EC767B873
  74140B0D-AF83-4516-AC70-B62BFA3DE68D
  C1FDFEBB-0DEC-420D-ABF9-AEC7A2DE5633
  79ECC4F2-F223-4045-A31A-565192EFAF49
  66E2AB9A-51E3-4360-B7AD-0B38EB0DD6E5
  C37D4DC5-0B09-4908-AB0A-E36F51F7D624
  E21C02A5-5039-42C2-8416-AA5D45E70CB6
  6C69C42B-3D0A-48BF-A5AD-43B350477387
  5510378F-D1A7-4642-8A24-ADA2D7F7E54D
  95427021-7E0C-4657-9B70-A7ED874FE35A
  DA96454B-FC70-4A5C-BD7A-E66D148EB1D9
  DD393948-C526-4216-BF9B-5869A7121933
  114B1269-7400-45A7-AC41-17032015FFAA
  401E2CBD-2769-4C73-979E-CA98F4F6208C
  C3AEB32D-5353-40E3-9817-C086F6BEB58B
  291CD491-B88C-4D52-B500-E7CC3095B3F1
  8E912802-3969-4352-9A13-25F434BB1402
  E69BDFE7-3E00-4C67-A5EC-8CD86E117DB8
  40E5417F-6830-4CB7-8353-4B5A7A08010C
  CEA03181-B97B-494D-B362-28056416469D
  9CFCEE92-D862-400F-A80F-7BB538B27B45
  D26E1DAC-F9CC-47A0-9A61-F32463247EC9
  9CB4A1C7-4798-4AC9-8958-9E3D86673D95
  F46C1C20-C958-4068-BF0C-BF6F4F77546F
  09EDDA89-63E0-4496-84EB-764FB9B0B7C3
  E1EF06A0-2C19-44FE-9AFC-C216671C9CA4
  BDF4AC96-F9A6-47EA-A27A-89A8D2B20BA7
  D0590D0B-4BE3-447B-A549-1C927BE0C745
  CA5F3B80-0121-4D0B-8DF8-92425F4AEBE8
  358A0E2B-B5E0-47AD-9C70-7BB72B1C548F
  45C83ABE-CFF5-4D00-9F01-F61C55525CA9
  2094BD8C-4A95-4430-A126-9A56255380F4
  B7C0C96B-2555-4436-9231-42670DB24838
  C32B20A7-11FC-4AB6-AE55-CC121B423A66
  F49136CD-0A8E-412B-9FC0-75AFB70502E2
  22821EAA-7457-4DFD-B150-CD5835AE05D4
- /home/ellis/comp/org/graph/lang/ml.org
  ED77C217-12A9-41FE-AA06-0B48FFF1FEBB
  83455E9B-53F4-46D5-AF17-1A9D732A7B2D
- /home/ellis/comp/org/graph/lang/python.org
  43663178-A6DB-4CD5-923F-612EAA8AE14A
  60CA4E95-2051-451E-A085-9C7095F410F6
  AAD902C0-22E0-48F2-AF5E-43120AC3DB10
  78AF4557-F1CF-4952-AA9E-D8F86B32FEE0
  98CD4E64-B815-44B7-AC00-6ECFA4863497
  102AAB0C-AF6B-4926-80A5-6E9295154996
  F73D72E9-FA3A-4953-89AF-2D10E5C0DF30
  3866C844-7509-4269-94A9-1FD1A99DAF41
  CFF089EC-31A2-446C-9ACA-FD426A4480BC
  FBF18857-17E3-43D4-B336-5A78C083F16A
- /home/ellis/comp/org/graph/lang/query.org
  90B5D156-6FD6-47DE-9E76-32E69115F5AC
  DA0AECCA-6D5B-4719-9235-6A11FE978B11
  3AC23A84-BA2E-41A1-9EA4-268E01891930
  2E7CC5B2-718C-4968-84C0-F881E702A616
- /home/ellis/comp/org/graph/lang/rust.org
  7DD61019-39F3-4706-BFC4-EA48BF76DA9C
  8FBE9DA2-1D6A-43BC-BD89-CF448D43EAB8
  FFB4E87C-E265-4549-91F9-093E714708C0
  C36A08F7-5FBE-4313-928B-A55636AAF20A
  79AD4134-5182-4001-B404-FAEB9ABD2474
  F10769F7-CF9B-4BB5-ADA9-D499AF348F9D
  BB68152D-1794-47D8-86C0-03EB7F9256D7
  B11AD05A-5D5F-4974-9364-C3EEBB9D15D8
  85F9F317-C6EF-4085-98BE-DB982B27A193
  5FFB08B8-D27D-4B1F-AE05-03DA0207CCDF
  EA2F3F8E-1C8C-4C05-B16C-FB197D346409
- /home/ellis/comp/org/graph/lang/shell.org
  EEDC1BF5-44A9-4580-8E79-3B83718E6A3B
  603A9A84-70EE-437B-9419-06E99FE431F3
  761BAF51-4774-4954-BE97-7B3AA53CB4D1
  B4048114-EC39-4E53-816F-2F1319D404EE
  9815156F-FCF9-4C33-BCB9-3719F2245B3F
  C1CB5688-A66F-43E7-8997-1AEBE845A7F6
  733D8D74-9F4D-407E-8A1B-FD40264CDBA2
  1DAB85A8-C52E-4185-A5D3-1AE182C5EE4E
- /home/ellis/comp/org/graph/lang/smalltalk.org
  EF41C99E-99FB-4A46-9578-73F8ED85B925
- /home/ellis/comp/org/graph/lang/swift.org
  D7B78CC9-8FA4-40AD-BE46-EA205C59E3DD
- /home/ellis/comp/org/graph/lang/zig.org
  24F9CD96-0AD1-412A-A24B-C3FA1BDF3C98
  65DB51E0-B2A6-46B4-9FF6-C76BB11B2CB5
  85CAB8FB-C534-4BD9-A2B6-16E31014D2C2
  B8C643E4-3D48-45C3-A61B-DB9613D1DB28
- /home/ellis/comp/org/graph/math/algebra.org
  3F69489F-80BF-4B1B-8113-AB8FD5E20E33
  C06444C9-C26D-452D-B264-413392B4B3A8
  AA739E26-BAEF-44B8-AE09-3162DF3E766A
  2547D30F-D965-44E1-86C2-B472C8B0D611
  FF07DF1A-5054-48AF-8130-22534DDE6BC0
  FA086B68-F270-4BAB-82DA-FF78844E6BB9
  78DD3CCC-9F07-49B3-BE76-4B133AF679A4
  E2E44287-6CDC-46FC-9AC5-CB4678831233
  0BFE9AD0-706C-4F7E-8CCF-27A48E7D4DA8
  CF6BEE91-6066-493E-941B-7171381AB508
  8208C5B8-462C-4F11-B935-246DE88E6667
  993236B2-FC86-4CCE-AC35-0730976A8333
  D94B3CBC-9DCA-430F-AF25-523FA12273E6
  0EBC3D0A-8913-49C1-B8A1-C62AC145B2BA
  14121452-3F4F-459F-9116-F8FDAFD8CD73
  757943F2-FE8B-4727-86D3-BCBDA1DD2536
  D0B0D9AF-FFAE-42C4-A151-1F947F348077
  ECA3FC3D-22C2-474C-9966-82CE724A0607
  B7E6DF5E-8393-4763-87A5-7183B62AD07E
  2054DBDF-D464-44FB-96B9-C3F41E006CA3
  BCAA674A-B485-46DB-955C-17BA5EEC4592
  4171E0AF-F048-4973-9D33-96B1F2B17548
  DF5C5EDA-929C-4F96-BBB8-99A751EEA4F6
  F66BF1E0-EF4F-4038-9DA5-06DCA676DBA9
  CEFE6101-7E04-451F-A69C-D831E5DDB4E1
  C93A7820-514E-422A-AF95-1DD6F8846665
  4C5EB400-B3F5-48FB-875B-F7A5F3C99EDE
  DC5499F7-FBA9-469D-9E97-14AE866D01F1
  B703C556-FD85-484E-954E-2F6F163A5752
  39130A13-90FC-4E04-A05A-ACDF31FC88AD
  82E956DC-69E5-4EEF-993F-6AFA97A38312
  FEAA8203-1DFE-4009-8A12-56B3A044D183
- /home/ellis/comp/org/graph/math/algo.org
  26E0DD8A-352E-4C57-B501-15BDEF909D88
  40C56580-D939-4985-BE31-FF7499CE7BEB
  C963428D-B5B5-4A9B-9912-AB8B17E3CF46
  16CA04AB-5406-4460-90A3-4D770BABFDF6
  3D34C56D-8411-4FCD-9FBC-8594A971DA50
  1E99ACF3-3BF4-49E0-AB2C-57C35341A7AD
  3942E7BA-1E6C-4497-9460-853F433CDAE0
  0205D00E-3BA5-4016-AFCF-03F888F5BD18
  3B982E80-DF78-423A-BA80-444954468057
  4E47C5EC-17FC-4BEF-B7E4-847957BE147F
  4E5355B6-8F08-44DC-A3C3-799019A9104B
  0756B187-0C00-434E-98A5-75E06CB3F01B
  2DFA085F-D853-4E13-A6CF-654D0F96B81F
  1BF44929-D8BF-40BB-B475-94CA1C631497
  C49D25F8-F2C5-462E-9742-CACC3796DA12
  299246FD-5153-4FC9-A8B8-0CE0FD097A88
  C2198CB0-16F1-4DF5-9671-6FC366116589
  6C336300-0BF2-4370-86E4-D670C079032A
  C6DD57AC-90AB-475E-BDFF-70698AB5A679
  A4B11C78-468B-40D4-AC37-9DDFC804A572
  2F14F7D9-A306-44BA-B879-5C211F189F91
  364BA4C0-2AD9-4965-ADE3-301EFB3406D3
  36FA7337-5B6A-4F5C-8B53-75B075F9803D
  F3D1F7DE-40D8-4DB4-B80D-4139AE2AB507
- /home/ellis/comp/org/graph/math/calc.org
  CB921570-B908-4B8B-BF46-D4F31B3E1239
  2DAEB26B-040D-4AFE-AC65-76FEB2AA2B09
  C832A0D6-26EE-456C-9BCA-4AD9B9D2A975
  D0976B17-9DE6-4C85-9AE5-8F1E89C4941A
  AC761EDC-8416-449A-9876-1564C57E06FA
  39D6876C-5605-4A33-9BE4-491F592D91EC
  35548C93-F79B-4393-BD34-F5914045C334
  A652DB50-8F75-46DF-8BA0-F196F4B7FB75
  8F56EA7B-0B22-4620-A454-A7FF9D9B5A5C
  4BFA694A-79DB-4EF6-9D5C-45515F70CB96
  5BB49707-E877-45FD-B2E9-A04D80AB4ECA
  C5B31660-AA39-4438-B3A9-28CA05368FE7
  8AB1326B-F5A7-4F6D-A870-C6B3274A8797
  A0EDDECE-2818-4F67-B557-D35118097D93
  C4185461-4A5D-4343-842A-F1031CB85A25
  04F5C842-E24D-455C-BE60-E0813825C14D
- /home/ellis/comp/org/graph/math/compsci.org
  ADC765C5-AE57-47F0-B220-6450DBCABEBB
  9C7D2D15-6D29-46D2-B6E9-E6B3670A6079
  08A0E9D0-870F-4E7A-B76C-DBCF4AC10F55
  1C09C413-4ECE-462A-BDB1-4F306018A3B3
  956CB941-DD29-4B70-B0F7-53AD71362ED0
  2B5B4C0A-C4E8-4D76-B71F-240D6707CB02
  E488F62D-462C-42FB-B62C-BF890E26499E
  762DD80B-BF45-4DAA-B693-2F34F1A61D3F
  DB309F05-7563-47A6-8205-901E4BE3F68A
  825B2467-A397-4FCC-83B6-C3397E9CC091
  A4A6AFF3-4FBD-4436-BA98-09299B5A1E41
  1DF49C20-99B1-4F0E-BBB9-6617B20810DC
  1336D625-E74F-42FD-B23C-292C07F9F029
  B0300E61-D29B-4DF4-940D-31257BF6A5F6
  9C8B77F4-E67B-4470-B2D3-20E6D3807290
  A316971E-8F63-450E-B2D9-8AD89ACAEACA
  FC02E09E-C2D2-4275-844B-2E104D6B6554
  60AB765C-7D94-43B8-ADB1-FED951E87393
  DF8B8DC1-5495-46D9-9CF3-7EE6E966F600
  695C0F61-3029-4EC0-A6A5-39A46A8885A2
  602CFF40-8E74-4C4F-9BAA-2C0D1BF5583F
  C934B053-1F34-4B81-B63A-CCC7CDE98B34
  959CC0BC-9021-465A-94F2-8314CC4EA07C
  0CD94421-590F-4935-B992-6290F1862483
- /home/ellis/comp/org/graph/math/dsp.org
  3DA5CB2E-53CF-424B-AF43-580FAB3E690A
  F0D573B1-CA28-48F5-B635-56B658E519A5
  1F95E329-908F-4262-AB07-542DDA4D0938
  D9739496-E662-4FC6-B4E7-864DD19A2C7C
  DF4C2E32-0921-447F-9333-BA5673A20D06
  0578C677-1D35-4A69-AD95-D2E256416643
  B5BD8C8F-5406-4C0C-A1AD-217ECC071191
  5CC94BED-B935-4E6E-8248-00D973DEBC81
- /home/ellis/comp/org/graph/math/geo.org
  3A9624B8-6638-4B27-8C8C-139720EAAEE7
  DE14F303-E4E6-4011-B5D6-E9F1AC04F9E5
  1C14070C-BB85-4F18-800F-D2CC132AFB39
  CF4927E3-B95E-4F39-A798-EAA48AA099B2
  9787891C-464B-4EFD-B0E4-EC973D7D0735
- /home/ellis/comp/org/graph/math/logic.org
  9FF60117-E232-4754-8FA4-85939B519CED
  460C0AC9-F37B-46BA-9837-21F6424185FD
  FB36A89F-2B32-452A-B480-5EA23BD63EFB
  D2BFFBA1-8D5E-4733-BE29-8E07C2CB528C
  6EEAB81B-C95C-4991-9E0A-D3C565DC800D
  160D9219-F9E4-4AB3-864D-5AA0DF3F9099
  4BEC80FD-4547-462F-9945-E4E524A018C4
  DEB87BB6-F5A9-455E-89A8-D539831D4D1A
  98845111-2516-41AC-822C-34DE16845340
  F159F005-C94A-4D35-8211-7355C2D8CDB2
  5BF53E1B-C866-4EE3-A5CB-53F56BBA9988
  8259478A-D303-4D05-AC00-505DECC39BB4
  A27FEA24-770C-4AF0-870A-8B697F97F884
  A6BEB83D-4595-4A76-B76B-AA72C91895E4
  A714EB13-728C-4AAF-8185-C18370FE427E
  23328BBA-A55C-475A-9438-8F86F5DF6F2A
  CED95C20-CF43-491D-9F73-D53BB01DA9D5
- /home/ellis/comp/org/graph/math/ml.org
  10588A36-BEC0-4A84-9CCE-179CBDEB1E4E
  C899B4AA-563B-42AC-8E01-F488107DD63F
  2A3605D9-9E3A-4743-9B59-E0F0C3C2C323
  21D6AF11-B53B-4E9C-A64A-35D9A223F479
  7A50D672-F3B9-4606-B4B7-3A6133C9B076
  D767B814-5842-4C8F-8B97-818B53759AC3
  6E99E961-7CE7-4D3F-86F8-66FDE8855F4B
- /home/ellis/comp/org/graph/math/notation.org
  1D101D10-7BEA-44EE-B41E-0E64C29D999C
  3B09B899-C1D8-42AC-BF8F-15195D70DC54
  B73D35E4-7A0E-4079-B97E-9523799EDC14
  16525C34-797B-4166-B504-9372DBD4B2CE
- /home/ellis/comp/org/graph/math/num.org
  791CAF84-AFBA-4D31-ABAB-5EF2C13D268A
  C51211C7-E096-4A4F-8BB3-235746D4879D
  F1BA9490-104F-4253-A5EF-34F7BB20E38D
  D778E8F6-DD0D-4D44-881D-ADCA28ADDC70
  65D76530-1DC2-4FAF-8C63-5945B16C5768
  C35BBE5C-2B2B-40A5-A30A-8D7A1817BBA3
  58CC61CD-944D-44A3-A3A5-D596117D6AAB
  D6BA8D4B-95BE-4D26-8A00-09DBD9BBED5A
  E02CDB53-6F30-4408-834A-71963374FBFD
  9991DA26-DAC8-48C5-B47F-63B4C8B9AB5A
  A466C60B-D698-47C6-B28F-D8A341FAEF51
- /home/ellis/comp/org/graph/math/physics.org
  873426F8-2DCA-46EF-BEF2-1FA1E3AA6881
  9F4D121C-27AF-4B5A-A54F-D77117880495
  68C944E3-DABC-401C-820A-85A8028AB049
  3328AE51-9643-469E-AAF5-AEC4C64338F0
  CEEC7C59-321E-4506-9A0D-61F56247F2F2
  0662E746-3702-44F3-B383-E8BFFC45AA6F
  A2901E49-A517-4D17-88AC-F789706C0E80
  653FAA00-7FF5-4E00-9A78-56B3C2E686C2
  E802B005-157C-485D-8281-713A85C4D124
  C7F7B48D-23CD-44ED-BE1D-223C4AF3D3AA
  BFC0616E-B631-4B74-A27A-839F25455C44
  7F7A4ACE-9070-4C17-B71D-EC68141CAE78
  B06D0C06-7561-4A7F-80D0-CF989A43AB15
  6D1698AD-B03B-4616-8D67-3987B1A83531
  90300EDF-9FA4-438B-8F34-65A6857CFDAB
  B4038FA1-5BBB-48E9-935E-293209907A8B
  0977C147-3689-4DC6-BDE7-C7EE9EEC5DB0
- /home/ellis/comp/org/graph/math/stat.org
  E986C340-2931-46E3-8ADC-BFBF0CD95BD4
  D48237D3-1559-46FF-83A0-CCFD3513A697
- /home/ellis/comp/org/graph/math/struct.org
  4850E361-E569-4B8E-A0E3-CEDCC7E4B3A3
  E2FD1FD6-2393-45A2-A073-0C44BFCFC2A0
  E70DCD77-790B-4588-8ABC-71B2F30C6A86
  2C184AE0-2523-4F44-9711-4E50E1C93C55
  A70A5D06-B227-4FAC-98EB-B371C5331217
  1E885A7A-5D8A-4674-B471-DB3E56837169
  8805BE63-567A-472D-A70C-6155BA2F3D02
  E2A9A550-500A-4E1B-B901-C988572FC587
  2616620B-782C-4C1F-97F9-E8F2D4FB8A38
  51E7D9AD-28A2-4284-94A1-18A642D0CF3D
  DF6FB174-7DAB-41B1-88FB-2A36572B7935
  BE0FC074-2CDA-4841-92A4-A16BC27E9EBF
  B4579E67-0855-44E1-971D-1A727694AF17
  67A3835E-7B81-4A16-9A79-C0673B4833F2
  9FFFAE3B-E504-46A3-8F30-9F47A00EC5BA
  91C3A4E5-B6C4-49E7-8B6E-EAC6E88E0B67
  03324C5D-0CAA-493C-993A-175CB3C9548E
  6DCB49D0-45E6-4C81-8299-D03CCDAF1633
  4240D8D8-A646-4372-8BB5-37D029B325C2
  0E58EFD5-14FE-4562-B09F-A92519084EF9
  9DA67FF9-B19F-47A9-ADEE-59B660672ADC
  61A74AC4-47FF-4F67-AFEA-E11BB4EBD809
  58645BDE-A83E-468B-BF9F-1984EB517BA2
  1C3DA977-929D-418F-9D3B-E59AC009C987
- /home/ellis/comp/org/graph/notes.org
  332145F8-50B4-46D1-8368-DDAF097C875F
  9A398886-858A-450B-9029-2339CC551BC3
  C2E682B3-D72A-41B3-B093-16614E7852FF
  A8B0DD7E-741C-4F5F-9D66-40B26EF56B14
  748BA6E4-60DB-4FF7-9D78-12C3F67644D8
  6C24DC95-EEA6-44FB-8C7F-BB49227CA7BF
  FAF8FBCB-3403-4E2F-B881-EF1404AD9780
  AB04FFF7-51C9-4F1C-B61B-FA4739932343
  08420B18-3856-4B62-9523-98FB3398AFCA
  CFEB1299-67C5-4A64-863E-F214E195E176
  435D84D6-C959-4BF6-AD37-FB6E524B54FF
  15115AB8-E7B4-4050-9567-BF026CC140D1
  21D776B7-9F8D-445C-83C2-8E0C28751827
  469DD142-BAFA-4076-8BA9-BAF088E60260
  E9D50E77-4D1E-4D38-90AA-9977D8C6C888
  84B5DFFE-7171-4D72-9788-F288E3185070
  30F4FB3E-0757-4DF6-947F-8D1E11EDABF9
  69B517F2-648D-4E44-B956-7879B3DADF99
  86E4195D-601B-4736-B852-1209A6D38BDF
  68AB3B7D-272E-4807-B2E9-959F182B8966
  9376D6E5-FE52-41F3-A821-0C2286DAF1E0
  026C796E-DCFF-4EDA-AD83-12E5D60F9971
  6DBB0064-1421-41BB-B2DF-36F694EFCE0A
  138F4A50-1D52-4E13-BF67-F225EF9F6747
  98E52E0E-104B-4DD8-B147-3A170163AEB9
  1C1BFAA5-53D9-4274-B4EF-621B7B52A959
  AA7D66FB-D93A-49B5-9BB3-2425400F5100
  02999B9E-D860-4608-8B63-80265D65F951
  1E0A7415-646D-470F-BAF9-448F93CFEF82
  9E96DF8F-0621-493F-BD3F-42E61B35D3CD
  46C01200-2B85-47B6-A471-BC042613F41A
  1AEDA444-995E-4600-847E-4EEA0C36A8FC
  5657CBA6-ED19-4438-B5A5-22E9DA9A98BA
- /home/ellis/comp/org/graph/os/mac.org
  EFFFD050-7F0D-4286-967B-CE8471D32147
- /home/ellis/comp/org/graph/os/mainframe.org
  ECE2479D-C9F8-4606-A137-7CA679CF7762
  70FAE18F-5A6E-4D1B-BA88-81339F13D0EC
- /home/ellis/comp/org/graph/os/unix.org
  AB57DCCF-C9F3-4347-B9D0-5731904F3D67
  4E8A9455-F1CA-4654-8CFA-562735661D69
  3E6B5E34-4CF0-4289-AFDA-BEA7C2A343DD
  EBDAD1CF-804A-47BC-9A8B-A8487F3B6E57
  46FDDE04-496D-45B4-A674-367EDAFB8054
  292A62FF-6D56-42E2-88FA-BD13DDBC2FB1
  EF769379-7632-4C45-B933-1E3BFD858EA1
  DA34BBA6-7CA1-4836-91D8-E16AE2A8FCB7
  7E8D965E-6B39-43BB-A69A-4747977B436F
  D77D5CE5-2857-4C17-BCAF-C3EB32F93BCC
  97D3D07C-E576-412B-A97A-2879EFA998C5
  CB4A79EA-64FA-4C3A-B4BF-F3F731BC04AD
  378227A0-D265-4272-8013-73DF72B5E49A
  94F363D8-45A2-4D48-9E25-17B1AC50771A
  5E859A3F-0C31-4796-85C6-7008B346F186
  93C4F02F-2B00-4741-98E4-F427530F4875
  25CC1E3F-60F0-401A-A8B6-AC8D5670233D
  CAED860F-FCEF-43A2-B080-94B01352CD43
  43020C04-F96F-4992-AD56-0BBFD4E55321
  DAE51FAE-66D9-4737-9971-999D3F94EADC
  AD25B130-D832-4109-84AD-7CB9900ED227
  BB85C1CE-9A29-4771-B6CF-5F22823CA600
  0DCB6857-91E1-4319-AD00-97C742604593
  F8CE343E-C866-4FFF-8E39-2DA32A59D56E
  639E5D85-E143-421D-86BE-9BC291BC2F8B
  9E0E0782-97CB-4B3A-85A2-B9DF08BEE962
  F35FF674-2A35-4863-A431-EE3D4DCBB634
  D58CB494-CE43-49CC-859B-AA6A518AC314
  EA9BB3F9-3607-4BE2-82F8-E9B3381A0524
  1F728D2C-EDF1-4502-9560-D0A6C45D5DF8
  C670FCEE-F9B1-4ACD-AB32-3B795748B544
  FF7219FB-EE6F-4DB2-A0DA-05546E09BDD4
  2452FE4F-DC42-49A8-8E9D-54F6F094F342
  85AFE36E-21AE-4792-87D7-84EFEB046CC3
  66441B6D-4141-4582-9F9E-75BCBC38339D
  F28B16E2-97E5-4575-A3D6-941EFEB8942D
  1F938C20-8D8E-460C-8FB7-F4AFAAC432CC
  AC0AE4DD-21D4-4B45-9751-A102A48F30E6
  CDE3FF32-1AD9-43AB-9AC7-05EFD3F88490
  5499A81E-1C6E-48D5-B906-9D2155AFC562
  8ED2735D-D259-4A78-8891-DED98F857846
  883DAF4B-7084-4356-AB2D-877A8AF2CD45
  19F3C5DA-0F20-4ECA-B142-7FC71095CA18
  0C37073D-0322-410B-8258-00FFD8215EAA
  9D49D145-2C94-4D6F-A4E1-5016DF6CBEDC
  74367B29-6A50-4EB4-AC6B-1C1B96DABD89
  92C2A9AA-6584-470E-977A-3547BCA79414
  D43311BF-7F5F-4D21-AAD8-4B35548813B5
  D494D0AB-53EE-4C01-8276-638351D86368
  1196E1FC-7D87-430D-9B68-C5A8A240B82E
  34966E81-AB92-4B85-B11E-073784261DB5
  C9FDD74C-0EB2-4D8F-BC22-0CF40996F186
  101C2239-6E98-4899-B552-17E8AE9C55C8
  CA6795EE-4B2C-4EC3-9BDC-F6BE67C2F1EC
  79C00D69-0624-4E85-A237-79E73E612DCA
  26B32AE2-B49C-42CB-A0D7-4823221B79F2
  0A40D25F-0FE5-4B71-9D22-07D4BB355FF4
  836933B5-3035-4E8C-A2B9-63A773A359DB
  6EF3FB84-6805-46F7-AD13-8929A023B43C
  F673F776-03C7-4DB0-AB0D-FAE463F8E8FF
  3C814D4D-8635-4C6F-A849-5C7D72DB20FE
  089909CF-4FD0-4124-A19E-F8EC619F8A63
  05CC62C7-DB2A-4BF6-B94D-E04A2B17AED0
  CB4A3977-F53C-4D43-A5FA-78D6D49B948D
  219F8BB6-B324-4A33-87E0-69114948C0F6
  06EE60A3-9A98-40D2-893B-39CE992FC0DC
  03215632-83DA-48C0-9F36-DF72A9E956B5
  59EB9925-EC78-4202-B42E-53456C04AC27
  133E5971-2952-45B7-889A-36DC77312211
  85F0992C-FC87-42DC-8946-0384DFE1CCB8
  A3078D9B-457C-4545-A058-098AD1BED196
  6C02FD4A-B7DD-4838-B39F-B84F6BA20E97
  1E726B53-266D-4020-A48A-0405DE5A0365
  5D1223C7-0DED-44B9-B494-3A3593A2FE02
  F03769BC-ABF2-4F58-809F-B672C66120F3
  4E717401-7B7B-4CE6-83C7-6F8420E01B93
  B52FDC61-2FCC-42E0-A1DF-66EBD0CA0488
  B54A3FEF-192F-4767-BEC2-C10058E69A89
  5CBE7AD4-008A-4ED7-889D-E7EC5663DFD1
  21E5A881-54D0-410E-B48A-F32EE26EF90D
  7C93B796-DC69-451F-9D70-BFB831F0E2FE
  45978AAE-AF9D-440A-93C7-C1D004B1F3A6
  37740E21-E0A8-4D09-9292-72BE229A65F9
  3C707AA1-BE3A-4258-BCD8-195216E658B5
  82110E71-748D-4DD6-BA91-22A6A41DF76C
  027A4EBC-2B25-4ECE-9A66-EE9BDC34D833
  BB21BCD1-4FF4-4718-BCEB-6BA0EF95D69F
- /home/ellis/comp/org/graph/os/win.org
  C584CCE5-6E64-4AD3-99AD-0D0EF2119837
- /home/ellis/comp/org/graph/proto/ansi.org
  F9CAB5E9-CD23-4EE3-B6F8-75D33257E4C9
  701737E0-2F23-48D6-98E3-316D472213C9
- /home/ellis/comp/org/graph/proto/color.org
  2EFF3580-A3D5-4A24-82BB-547EE01C252E
  AE26908F-4D58-40A5-8F17-0DE44ED51F9E
  DD0D78ED-2363-4F49-BA06-287346912F99
  29544197-B72D-4439-9729-BEA0B5B0AD63
  4B5BD7A3-9782-428F-B43B-5A854362DB2F
  80C7B6BF-BD35-4C27-8C8C-B4AF87724C41
  5889BD44-C0A1-4CDF-AE87-A0DE4CF77214
- /home/ellis/comp/org/graph/proto/crypto.org
  5ADD36A0-129F-466C-B493-B34AEE8B99A6
  6723D8FB-5E3D-4B38-96D5-3B054DBB7B58
  46E1E3DD-7C47-45BB-8B78-18A87B7258DD
  DCE824FF-24E2-4BF1-B0A9-B42F778DAD39
  2F1C6753-397B-4AB9-9457-4E0136C6BF8B
  123C1580-8DCA-4773-8879-9769EBD84AD0
  B754EC14-7D34-4504-9494-93532BD61CD5
  ED65B25B-8C80-4209-A490-0E9F18B9BCD3
- /home/ellis/comp/org/graph/proto/dat/config.org
  82949E4F-537A-4A3A-B901-06080EEC82B1
  1507E902-F244-42D4-9BC5-C684162A3AA0
  E2E6F554-2D28-4474-A1ED-3DF4557E091D
- /home/ellis/comp/org/graph/proto/dat/cue.org
  557AF15D-FAD4-41F8-B652-81B76D618401
- /home/ellis/comp/org/graph/proto/dat/deflate.org
  6F46C6F3-32A5-4932-B2DB-687EA4C8E04F
  CEE22050-4AAE-4735-BB53-5C6253AA21E7
  7E74E117-69D3-4261-A869-6E7389769E4B
- /home/ellis/comp/org/graph/proto/dat/exe.org
  F24FC678-8FE5-4625-8F57-F1CA6465D007
- /home/ellis/comp/org/graph/proto/dat/json.org
  F4898B34-2F02-4403-BD1A-3FC984007BEB
  A6410358-EE73-41E6-A8F7-271EDDA02309
- /home/ellis/comp/org/graph/proto/dat/m3u.org
  293BF186-AAC4-4501-9267-08877FE0565C
- /home/ellis/comp/org/graph/proto/dat/parquet.org
  07FCB963-C208-4735-9ABB-3C55C2340A5F
  E71F388C-9ED1-4862-8890-7F74271E8DF0
  AE54516C-C8A8-49F8-AAC6-A95C18F5DE8E
- /home/ellis/comp/org/graph/proto/dat/rdf.org
  69D2206B-C9BF-46FF-A354-D6428863559D
  9DCB0F55-6BDC-4B81-A7F5-4C24901596CA
- /home/ellis/comp/org/graph/proto/dat/sigmf.org
  13226398-1931-44A5-8914-7EB2BE0C345E
- /home/ellis/comp/org/graph/proto/dat/syslog.org
  F8CDF36A-9BF4-46BF-B33D-8338274FF9DA
- /home/ellis/comp/org/graph/proto/dat/tar.org
  7615CB48-0257-44F0-BC2F-BA13307031C8
- /home/ellis/comp/org/graph/proto/dat/xml.org
  C73D296A-47FE-4769-9802-86CAC8A86090
- /home/ellis/comp/org/graph/proto/dat/zip.org
  44562F82-60B6-4D89-9346-C0D5525E86C8
- /home/ellis/comp/org/graph/proto/dat/zstd.org
  237F6FDA-1B69-4ED3-A58B-28473C9EB3B0
- /home/ellis/comp/org/graph/proto/desktop.org
  E0AD1796-3D1E-4026-B019-E212756A205F
  D34F4C76-4CEE-4513-B172-C2A6034C2048
  460BCB30-97C5-4A69-AC91-BB357EA7C238
  03FFD6C9-5BE9-4BC5-8006-4973A098AB6F
  6F534214-A89D-4CEC-9C29-0F345FDC2199
  1B00B336-268E-4203-850D-12CB8B79C86C
  F0A4403D-D5F1-4F7C-8D56-AB235ECB16DD
  EB66D5E4-E0BF-4F4A-A935-0FB30365DCA2
  BDE20E62-DCD9-48FE-BA2B-BF795ED81A51
  1E4E50F6-1336-4D5F-9D3B-8F361214B523
  0217D049-0CA6-42ED-91F5-682BD9B8BAE2
  F8211C8E-3F31-490F-A5F6-89B1D963C4F1
  379EECF3-BE0E-454B-B733-6F9AAECFC83F
  0E881B59-DC08-4A50-BEF3-F5E98B7A7B07
  77036A2B-8429-4FF0-97B0-D79166EC4028
  E26FF2E1-3481-478F-853A-F72FB9D5DA6E
  83A5DD29-C5C7-48C3-8C66-D4F151261818
  B2202607-E3D6-4E1D-B71A-1B0B3BEFE1DC
  EABB4E88-738D-42D2-986D-E5FFDD4C6FB5
- /home/ellis/comp/org/graph/proto/font.org
  D53D8503-A27C-4556-95DF-45CCCA5E33B0
  4EC4C00D-BA44-4B58-BC37-AA92437C0608
  4F5F11E2-3FFD-4523-97C9-D5BF17A64EEF
- /home/ellis/comp/org/graph/proto/ietf.org
  5289575F-F017-487E-9A42-5474B1688023
  3C8002DA-BE9E-4AB3-BB78-4BED103C87D9
  C037E608-0DC9-410F-9891-A6A1FC9356B8
  B1ADE942-68E7-4BB3-8134-CD256AD5A428
- /home/ellis/comp/org/graph/proto/ipc.org
  21985279-2724-45BC-A472-8FEB9540F705
  44D2A4FC-B42E-49B3-9AD6-84A90B5CBD38
  E6BEB962-3B43-4D81-B1C7-17CF062327F9
  089BB9CC-9F1F-4810-B24F-DA40D7A3AB87
- /home/ellis/comp/org/graph/proto/iso.org
  C0578A29-1C02-4BC9-8396-8ED5F637078A
  89B31B74-EA0B-4873-8058-330C9FCCC772
- /home/ellis/comp/org/graph/proto/mail.org
  3A05DC16-8FAF-4004-A2CA-26F2EEEE5DD5
  1CF5B67E-E476-48A9-9560-7E0D49DE9768
  3BDC7566-668C-4332-8684-7CFDBCD71C8F
  F1D8108D-F9FA-4AB6-B1E9-CA0B932552C5
- /home/ellis/comp/org/graph/proto/math.org
  0DE50AC1-75A1-440B-981F-83432258C1CE
- /home/ellis/comp/org/graph/proto/media/audio.org
  0FBD2A5D-7AEC-47FB-B896-588908CEE38B
- /home/ellis/comp/org/graph/proto/media/disc.org
  94958BD9-37BA-4B96-BBCC-FCEA8BC58C29
  4473478D-4A0A-412E-8426-9A5C818E11F6
  A8469289-6309-42AF-B5CB-4F1B59EC8307
- /home/ellis/comp/org/graph/proto/media/image.org
  589B5025-B95F-4271-806B-E6960C4FB0A0
  9FBE4894-4557-46C4-B602-99823BD2EA66
  EE2A3B64-3A16-4056-A6B4-2514495F7CCB
- /home/ellis/comp/org/graph/proto/media/matroska.org
  FE84EED7-478B-41B3-99ED-A2DAC53E13E4
  25692E81-F783-4706-9066-F30C13CD212F
  8C02DB6E-9D72-4C4B-BE22-01C279B2532B
  A1270838-1777-428E-89EB-513E3F86C63C
  A4B8ED28-0E02-48C0-BD2B-FC05B05361D2
- /home/ellis/comp/org/graph/proto/media/xiph.org
  BAEB9EB2-4A29-48C8-AB6B-08D6435B3DFB
  4C24558C-D32F-4509-8CE2-AC8293664258
  D903A0AD-3935-417F-BA42-2BC4B11032ED
  69073A0B-8DA4-47AA-AF0B-F068996C96D5
  F4EA47BC-DF51-43E6-9CFB-AE654F89ECC0
  22F5EDA2-007F-43F7-8924-10F551DD440A
- /home/ellis/comp/org/graph/proto/metal.org
  533C2390-63C9-4CAC-B0FF-2E7E93B4C60F
  60DEA93A-8C06-4370-B89A-832A27772B9C
  4E5188F6-E84C-4C48-A879-901426B73295
  6F908314-D6D8-471A-96C7-E388F6891FB0
  8992AC90-C5FC-468D-9C41-AA5388DCBA80
  FE64EDB6-9F78-4AB7-B488-72B0F8232652
  AA3EBD09-D9F9-4917-936A-A784DA9A8754
  4748E13F-2F13-4718-96D0-7C1649F31DE9
  248F0DBF-971E-46E9-91A6-7F6D06356C19
  7F759436-4087-455F-92FA-1DC49D5DBCFE
- /home/ellis/comp/org/graph/proto/net/audio.org
  D6DC411E-6990-4497-A32F-8DF115E9DBDE
  11E0BF92-88AB-4629-B52B-5D3AD68E2A0E
  5EAF463B-C57E-449B-AE51-556871A42AEA
  ED1AFE18-5020-4DFD-9E54-2F9533BE4AF6
- /home/ellis/comp/org/graph/proto/net/bonjour.org
  53C882FB-18FA-4F6C-9150-00C0769F834A
- /home/ellis/comp/org/graph/proto/net/chat.org
  13368FF1-B66A-4F98-BEBA-BB7687D963F4
  88D5DE2C-D58C-4B74-9E28-30AA36355EBC
  5A2444F3-4015-40E3-B3D9-6CED04C2C989
- /home/ellis/comp/org/graph/proto/net/dns.org
  78F84075-F759-43DD-BE98-B23ECCF26333
  8E929D14-5562-4E6B-8ECC-41245FAECEC1
- /home/ellis/comp/org/graph/proto/net/iot.org
  291AAAED-2490-4B11-9832-A27DAC406127
  883946AB-69A0-4A44-A721-CC3909572E80
  7C4C8F35-EA95-44E6-B27E-2F1392669177
  0AA98058-3A76-4A20-84A8-0990CA6B604A
- /home/ellis/comp/org/graph/proto/net/ip.org
  2C915D42-3F42-4A94-A2D7-AF73C9938C7B
  1F6E6B6D-A64D-41D8-A60B-898C5024A87E
- /home/ellis/comp/org/graph/proto/net/iscsi.org
  404D8C7B-7440-4A8F-99ED-BAE74CC37FC5
- /home/ellis/comp/org/graph/proto/net/lora.org
  B611B0F0-9DCB-447B-ADDA-1BFF7C61BB9B
  CA1597B0-7BF5-48A5-AF93-6CC2A573ACA3
- /home/ellis/comp/org/graph/proto/net/p2p.org
  29FCF858-C4CA-4315-A987-DCE397465F17
  2A37FF6F-3A34-4659-9C93-E72C86DAD411
  9D5EBB0C-2354-4522-A652-B60DBA0FFAB7
  DF23C94A-ED42-4BE5-B7D9-351A4205B4D7
- /home/ellis/comp/org/graph/proto/net/ssh.org
  F8D6DD49-942D-4621-94CB-D1B01032240E
- /home/ellis/comp/org/graph/proto/net/tcp.org
  A2C33F5D-8E07-4122-98DF-72D321AE313B
  52A7CB9D-5B78-4681-9146-2D8F5707C1A3
  5C9B8B56-6C37-4171-8DA1-AC6E4E3CD0A1
  95274690-C607-4C94-9416-707F478814AE
  2D727CB5-B30C-47F8-B208-ECCD1D32D40D
  81E78198-A5ED-4FDD-B487-1BB3874FFA71
  C0CC13D2-F8C2-4772-9A1E-86E406E118BF
  3CF5D8CB-C70B-4BA3-A166-D69E740A5505
  407F25FD-AAB0-4AA5-A994-ABB1BE11FAE5
- /home/ellis/comp/org/graph/proto/net/time.org
  4673D7AB-AA8B-497F-A86A-630E4DFDB49C
  36E7B014-2780-4941-BC17-7C782195EE8B
  76E01D38-9C42-464D-9EEE-D13DD4BB4E55
- /home/ellis/comp/org/graph/proto/net/tls.org
  A81FF891-504C-404B-9B7E-046D097B3C95
  10E75A1A-1DE9-4DDF-A5B6-4B077D4CD4B1
  D86E9213-BE13-4A37-B90B-0CFA2F0BA16A
  08A538A3-D974-4185-A83D-1A9207AC04F5
  692B4EFB-CE4B-4D7B-A100-685815164CE4
- /home/ellis/comp/org/graph/proto/net/udp.org
  A2F33EA0-51C3-45D8-8C19-03A95321384C
  F7E112CA-25B4-41F1-A756-2492EDA9DD90
  D3E91177-AD7F-4D8D-82D9-5AC09F786774
  7F5A6675-3E8A-414B-8788-C9957708BD79
  031F06EB-B4A6-4386-A17F-33712BF67181
  530FBB93-E34E-45E0-B62C-4E9A5022649A
  33AD3584-2728-4F90-8FAE-397F026731F1
  989AE244-F798-425C-BCF1-32014EAFBD22
  19C29790-17F3-40F2-AA2B-03BC7E0BAD68
  E7E88A43-5294-48FD-84DC-9F90A4AE193B
  B141732D-DDF9-4EC7-9E47-F64AD3A0C662
- /home/ellis/comp/org/graph/proto/net/vpn.org
  17DD76C0-B08B-4DF5-B9FB-C1DD6B84D812
  B01BA656-940F-43BD-AE92-E0AC3B142028
- /home/ellis/comp/org/graph/proto/nist.org
  F017B5D9-67C1-4F7B-9E59-F3EC8C4EA65C
  F7405F68-480A-4228-B3AB-AB35D73A7C25
- /home/ellis/comp/org/graph/proto/opengroup.org
  AB5E5BEA-2600-4BCC-B0AC-BB4A9A6C6D0F
- /home/ellis/comp/org/graph/proto/unix.org
  E7CA2D17-05FC-4262-A4EA-F6100F3B8B62
  60EA3E74-F3FC-4A92-87FC-AAF62A8F532F
- /home/ellis/comp/org/graph/proto/web.org
  86847E74-1DC7-47E0-B2A6-6AF03555798C
  F38A19EB-18C3-4B48-851B-745B839DD1E1
  78FF8DDB-CC33-4538-9157-1A11CC04248D
  48415094-068F-4956-B841-E84442747585
  BD9C1355-D21D-4F6C-AB60-042BD737DE60
  602EEAD7-B934-4419-B3C2-276E90E91F7D
  BD692828-EC5D-41E8-BBD3-6DC0BDB61DA5
- /home/ellis/comp/org/graph/refs.org
  23D6A3CA-50A1-4116-A4DD-BAA3EB190E8F
  7E2728A6-A6BA-46FC-9521-04640150902A
  4B57D0D4-99A5-4EED-93CC-65AA5EC501DE
  38641ABE-2D29-42FA-BE0D-2ED2587AC85D
  838A2CAB-5459-4B85-9DB2-045E57CE4B2B
  75E6F448-883A-4A7E-BD2B-81A567AA6936
  05943A28-0A59-4EA6-98CB-A7C994A55A0C
  914B352A-2261-4BE5-8A78-3E82DFFAA3EE
  4B4F817A-BC65-4E2B-B12D-D80C271F0A8B
  49778B54-1643-4427-BDCD-D4D271DDCC7E
  87030924-1E5A-4654-9FC4-4C8F493E5E80
  D6B642F6-4743-47EF-ABD7-0989B6B12751
  1ACAC1AD-4D03-416A-9161-EEE23DC93ED5
  B3A9DE3B-E367-4B3C-9DB6-664BC4060AF5
  C96448FC-FB08-4F6D-8219-D6BFED913D26
  D61CC9ED-13E4-40FD-A1DD-6E23422643DE
  54DC4914-97F1-4FD0-ACAA-C8ABF4460765
  E8926B3F-20C5-4447-AB8A-319E565923F0
  7B6FA71A-EBAF-4E47-92E7-2ECE601C52EF
  9E7A4C5C-168A-4D9C-95CA-7A51CF20BCD0
  2EFB21F7-BC3F-4C74-9757-0620D5A7CE8F
  8C4460C8-F01B-40F9-BEE9-B1A7BE141C2D
- /home/ellis/comp/org/graph/sys/bin.org
  A5DBD081-A23F-4A78-B2DD-F32AF6EBA984
- /home/ellis/comp/org/graph/sys/db.org
  A833EB98-C31E-4492-AC07-E718A9BCE086
  F239F934-A477-4050-8D19-3C2597A64B34
  03AA2C81-5318-45D7-853F-BBCFDB8E7D48
  999C2245-1E81-49C5-A0A4-6BA4D18EE132
  7F41F3EA-FD20-410A-9DC8-BE188220A382
  3BD5F5F8-956B-49A4-B280-EEC4A8C0F85E
  B569A646-DE4C-4287-8599-52B237A753B4
  3CE0B887-31EA-4A78-96A2-6671907A687A
  DD24CE27-3907-48E4-8B5D-8BE8B2035AE1
  9933D695-6379-4903-A4D5-0AA887BFA7D9
- /home/ellis/comp/org/graph/sys/fs.org
  8FF74861-A0BC-49E1-83EB-3A32F8F8FB78
  3E7BB82E-7DAE-476A-8ED0-18C361C9BD1B
  2B662144-97B2-4736-A8FC-BC8F861B9829
  9DDB1CAF-014A-4D0F-972E-82028E8BE286
  7535F844-330B-4F9C-B2A1-4578D64ACBF7
  1D1A6211-C91F-48AE-8113-0DDADA286CEE
  BE04DC90-86A6-46C5-9DCF-25519EBED34D
  3C828873-641E-4846-ABD6-781605F33F60
  A5DAB699-AA5F-4862-A733-90E62EFBEAF4
  A879D61F-2AC0-4755-8E1B-C80B2477BBD6
  55DB3738-F09F-46D6-99E3-BE4232CC14AD
  9F0ABBB7-4636-492B-AE4D-EF09CC1F6EF0
  5DCC3D7A-8D3E-4EFD-9159-45D9D528429B
  E16F0072-F857-450C-ACFC-F4D3B9D1F852
- /home/ellis/comp/org/graph/sys/ide.org
  EDDAAE08-A0C1-4413-9F0A-804F663AE176
- /home/ellis/comp/org/graph/sys/mem.org
  E485721A-4CD8-4BAE-8D62-45E11729DA70
  2AE80374-CB47-494A-BE51-E7F267F80A99
  2F1F89CB-1B42-4155-B79E-B531659323AF
  5CE30140-63E4-44DE-B1A2-AECA8D967075
  613D9983-6681-4BF7-A99F-C098163F655C
  E87B4DE2-E614-484B-A4EF-97D1180F1BD0
  E6C79B21-6762-48E4-9168-D314C5761F8F
  A6957FBD-69A1-4123-BF2D-31B98C38BE02
  0494BAB0-8676-472A-8EAA-1CFF42B932D0
  4D872F6F-61A0-42D5-A5C9-5325BD8F184C
  03C44887-96F5-466A-8D42-7DF51FD42EB5
  CFFC8C70-D0BB-4AF9-9B1C-F9FD7C5B081C
  EABF2D7B-C99F-4854-A64C-397FF8F90A2B
- /home/ellis/comp/org/graph/sys/pkg.org
  DB7D826B-F528-4798-87E4-F82427A25855
  F22BB870-97E4-41A5-9E00-31939861A7DC
- /home/ellis/comp/org/graph/sys/srv.org
  DA8AE0B8-ADCF-4639-9CFA-01B7B9FB3C44
  65E192AD-9468-4C16-884A-470A2930471E
  27DD8C6F-E018-4C91-9113-325BE8EE483A
  5FB03F4F-E7BA-47FE-A502-185348417AA4
  78C7AEE5-76B4-4062-A8B1-5E04B252DDA7
  C98F568B-46D1-4A82-9322-CAA73CC0A38A
- /home/ellis/comp/org/graph/sys/term.org
  B5F81528-C53C-49F2-B1C4-68D886B65408
  A9F72C53-352F-4856-A910-3664CE020E2A
  39F3FEB3-7FB0-437D-8589-78D2CF4FDA31
  4B456111-6A79-4F6A-90AC-A815F5BE618C
- /home/ellis/comp/org/graph/sys/thread.org
  019B5A13-DF61-4A01-971A-4AC48FA5C617
  144255AB-4F31-46F6-A627-4537090E6DC5
  B1914866-4E35-4D6C-A8F3-4B71B418C199
  9AC2D388-81FF-406E-88BE-8ABDD210B916
- /home/ellis/comp/org/graph/sys/vc.org
  36CCC6C1-1B2D-4A48-8C1C-714A43873407
  442C8FBB-B09D-4F85-A068-2A0F6A2DE430
  BE8E9117-4D72-40EA-A062-8029A3342248
  879ABC56-8968-43CC-8BEE-76118B398EAF
  11BB8531-A936-4B77-A29E-1E2D35436836
  B750A5F3-F12C-439A-A730-1DCEA8951D43
  0DE5A5A3-0C2B-4F98-9777-65A88EE0FEBE
  A62A2E17-8167-4812-B5EC-F4F9EF698F56
  E3DA871B-420E-4221-889C-FFB62E928776
  F8829131-67EB-4D4D-A101-28F08ECED9AE
- /home/ellis/comp/org/graph/sys/vcs.org
  36CCC6C1-1B2D-4A48-8C1C-714A43873407
  442C8FBB-B09D-4F85-A068-2A0F6A2DE430
  BE8E9117-4D72-40EA-A062-8029A3342248
  879ABC56-8968-43CC-8BEE-76118B398EAF
  11BB8531-A936-4B77-A29E-1E2D35436836
  B750A5F3-F12C-439A-A730-1DCEA8951D43
  0DE5A5A3-0C2B-4F98-9777-65A88EE0FEBE
  A62A2E17-8167-4812-B5EC-F4F9EF698F56
  F8829131-67EB-4D4D-A101-28F08ECED9AE
- /home/ellis/comp/org/graph/sys/virt.org
  83B24CD0-3C89-400E-B63B-64872569222B
  94419FB9-0726-47A0-B416-DCA75E9A508C
  EC17DA11-A3D1-4343-9D0B-09C63C569DB5
  0D6AE769-8E04-4209-B34E-07BA8C9352FF
  C7733E64-1370-4586-94E1-DFAD81080160
  86B9ED90-DBC4-4EE8-AC8D-842EF0B39941
  858D93BC-65B8-46E5-A8AA-342A14FBD20D
  10174B54-9C6D-4AF8-A782-F6B3BB3DFAC7
- /home/ellis/comp/org/graph/techne/percussion.org
  0E67F399-B0D5-4744-AC55-5D96CF40CA5A
  51AEE2CB-55D8-418C-B2A7-D20102AA07CE
- /home/ellis/comp/org/graph/techne/piano.org
  8A252132-1C2A-48E1-93A7-B2E6C87691BB
- /home/ellis/comp/org/graph/techne/synth.org
  750C57F9-E4F3-4D15-BAF1-893B25B4ED5C
- /home/ellis/comp/org/graph/theory/ai.org
  CD514A66-4979-4983-8C9B-29B54EAFA8DD
  976C3073-07C5-4901-BB64-2B2E2F799170
  789AA097-5F4A-4131-B9BD-0F153F8DF88C
  69642814-C551-45D7-997E-CE068CCACE02
- /home/ellis/comp/org/graph/theory/compiler.org
  439686D0-5275-4E0D-8EAB-B6FD87D7A547
  3638F1D2-EBC8-4BBB-9242-4E6070A3B121
  9E3802E1-6E58-4A5A-9A30-509E25122D31
  23185C5D-7470-4BF5-A700-99752C334333
  BBC6FA80-3C38-4EFA-93FD-B0416D4EC16D
- /home/ellis/comp/org/graph/theory/econ.org
  F21933E9-5FD6-4CC8-A964-2B75C753C8D4
  6E111491-9CA8-4535-9642-D0BEC178EED2
  B579B27E-6057-4012-9503-0EB710490EC1
  F346F656-C938-46FA-B1E8-334C1EBA3B21
  D3A6A367-5817-4BEC-911A-87610EC7DE92
  6AE0C23A-7BAD-4D49-A816-EBE403A65009
  4E85CC82-77A3-4722-B31D-D172BAA2374B
  A95711F7-05C1-4156-900F-5B7644413090
- /home/ellis/comp/org/graph/theory/hacking.org
  904371DE-EAAF-4DF9-A9DF-4A2A443F2066
  FD1C94CA-18F8-420A-9EE5-2ED7B6DDFB9B
  598FC07B-3EAB-46D7-ABD2-510EE8135584
  2AB524EF-E77E-4482-B563-123B556F431F
  85167C32-6E64-4689-81F0-85DDBEA58BE6
  86C6D5F6-4212-4DEF-8D24-AD872D73B55B
  305A678B-80E2-4C27-8AA6-F3895AEE3415
  C07E50BF-57E2-48B7-9FA3-7B9F4C0C35FD
  A3DBCE54-1677-4D11-9716-13574D25ED65
  C6DF0DE5-0B3B-4E6B-8F82-B44859E2310E
  B8B4DA43-18A1-469C-A256-8336FDE50DB8
- /home/ellis/comp/org/graph/theory/money.org
  1488CE14-B340-49ED-BA7C-CBECF8212B47
  5BEA8DAC-44FA-48E6-B7B6-4F971FAD73E8
  5F17B96F-915B-460D-A60A-4B9BC9D7B007
  D542BCE7-708D-4067-9D59-7835C64CE098
  FE283E63-250B-4772-A252-444F2CDE0D3D
- /home/ellis/comp/org/graph/theory/plt.org
  3A1058DF-158C-49EB-BCC5-21B842EC966E
  44659589-80A3-459B-AD29-D2E5B208B451
  7DFD88E4-5511-4FF8-99CE-0FBF464BDE58
  2CF671A3-F33D-420E-9A9D-2EEDD6CDCD43
  5FD4A7B5-2D71-4373-8C56-F65461E4D633
  E980058D-60F2-482E-96EF-5E7323CCEBF7
  4BBC6288-B410-4171-AACA-DB1C9BDEC7E3
  84CEE9FA-D517-40E9-A7B9-8D8DD5D84DEC
  F48341D3-F9AB-44AC-9387-4D32E92AA011
  AEF61327-6C27-466E-B7C1-5663998A0824
- /home/ellis/comp/org/graph/theory/process.org
  4B96AEF0-69CD-4493-BE15-9BA0D62012C2
  DFD57E14-4EF7-4BB9-9B86-0352CBF14C90
  9D05F7B3-FC57-41EA-828E-F482BE342BB7
  B597822B-B956-4959-A5E1-6BF42C191320
  4700F502-0BAB-4887-B925-224003CC3663
  C95BDAB5-CB4A-4530-83B9-E152D0A2E41C
  D181E466-49D6-4421-9282-D227618C5188
  567CF0ED-447C-4EEB-807B-99F3376CA508
  49DC5FA2-EA40-4532-91EC-D3C00CA9DF6B
  D4140692-EBB8-478E-B933-062726EFA859
  BD66A9D3-9720-4DB6-9D29-CB5EE241B8A5
  E8371372-77FA-4E44-ACA1-D2D5EACC7FB9
  54831DDF-56D9-4307-A7E3-3790B13C6C9E
- /home/ellis/comp/org/graph/theory/style.org
  6B994F9A-2584-4F8F-8739-D9D70847E8AA
  25FEDE3D-355D-4644-A0EB-DF2D828157AB
  10CDEED6-9DCA-42AF-9B33-3D2A6ADDBDDC
  483EF3A4-C1D8-4FC4-988A-03E9F5E789AC
- /home/ellis/comp/org/graph/theory/system.org
  F08E3BBB-44CF-4036-8FB9-406D9F030F4F
  69E45A0C-8352-4810-952A-C81B0F99D21B
  05411345-EDB6-4EAA-9353-D7164FC8E237
  5DD75B6F-6245-465E-87F5-E944C4B836F6
  B34A9D4A-7FF0-4566-8CD4-DCE03CD0EE05
  18BE5216-CF69-4472-9FEE-9A325EBA6EE8
  AE2EADD2-E305-44B4-BFF3-952AA09D2943
  3A641C7C-5532-483A-B64F-C0B401970A5D
  0E6B0635-A1ED-41FF-9129-A2E72461DC0B
  FCD2D202-B02B-44A7-A218-59B5BFECA1C7
  BD25630A-B72A-46C5-ABF1-733F5C892BF6
  B6486B7B-506A-42A3-AAED-7CD476884340
  E976F7EC-0EE0-46CC-8B5A-29AFBD713FED
  ADCD747B-2FDF-4686-ABBB-26940BBB1A20
  33392043-87AF-4826-AE73-1D722EC650EE
  7F92B7D3-8C42-4D25-849D-58928BC12EBB
  D20534DE-706B-43CB-B1E9-F054D534A848
  0881A735-21EA-4509-AA97-B2D239CBBAF0
  188C1D7D-879B-4A72-A963-AF278DB56F99
  DBBE76E3-42AE-4CD3-B39A-A8C8D3A7C7C3
  8889AE64-A982-4F6C-A875-5CBAE6DBB323
  DC13038B-91BA-4A5C-BC62-AD189033023D
  B337E6F1-9340-4F2B-B840-08D57B5FC5F8
  1D6DFD1B-692C-4253-A364-E0E63B2CB048
  5773B3BD-37CD-406E-87AD-A041389F4198
  7EB1D3C6-606D-425D-8C2B-3847E42F0134
  10F68FE0-0451-4C43-B61A-69ADF139F060
  7936ACF6-F60D-49E7-B09F-6C2FA0D8A623
  1A791C60-412B-415D-89BC-06FF9D166931
  9574CA65-E7F3-40CF-94C1-F05BC6628FD0
  9464F3DF-5D9A-4EC8-A629-4C080399D664
- /home/ellis/comp/org/graph/web/data.org
  59E3BA53-3F40-47DB-929C-ACC998F9092D
  A9659676-999F-4EB4-B841-DD3A2E383317
- /home/ellis/comp/org/graph/web/orgs.org
  BC366321-EE96-41A2-A70D-FEE9FB7E49FD
  93ADDFFD-BF75-4D66-8FF4-6A727D0C3D81
- /home/ellis/comp/org/graph/web/sites.org
  0EF132B4-D324-4BF9-86D0-94ADA3EF04B3
  218869F2-D154-490B-AB0A-88FB23CA0368
  6448B881-6310-4F17-9D3D-874EC5FA3972
  314F6109-DB30-45DE-BDA1-3B1084224B40
  9EDF9C19-DE57-46F2-85C6-8DE9DF888057
  8C348A7E-3D6C-4EE8-9BD5-1E57A9754A24
  52F85631-E0B4-402D-8300-3B0F96CFF72E
  B03233CD-2DD2-4DC8-83EA-75F74981C4FA
  67CD18D7-3C2D-461C-A61E-32CBFF5BE10A
  246F5FCA-C142-4C9E-B5F8-E59BB89FEB9E
  D3271956-F2D8-41CF-AB3C-02B7F86E6CF4
  AE7CFA47-AECD-4CE4-A0A7-19F71EFE12FF
  29407696-FD6E-428B-85A1-5616BAF554D9
  EB20A9F9-4C80-40D5-B4C1-153C8976DB19
  005A209D-C429-410E-9CA0-F347B0FF646A
  8E4D1A1B-9497-4291-B9FE-6D814B6935B4
  537C7ED7-C5A3-43A0-8636-6F9185711622
  41DFDEB8-E1C8-44BA-8235-E48DA9C0CA32
  99C4FB1A-715E-45AA-BAC8-CD588FAC8F0F
  9CAD378B-BB5D-4005-9059-D8AC639CA85C
  D6D95CA9-2B8D-48B1-B1F5-FF6E9167EA27
  043F7B08-ABCF-4727-A772-9B64F7F43D58
  04F8BF69-E4BC-4A5A-83BA-F211DF606857
  0C83FEA5-C697-4409-961D-440A9BA2B548
  0459C77D-86B9-4FBD-85FC-485C8923D457
  86DF9EBA-9175-43C8-B083-D263CF0C800C
  58E80E6D-E99D-46DB-8DA8-FF397A304FB9
  15830F8C-99CF-4034-9DF2-86AEA530A8CE
  DC19BB9A-3F8E-41BA-B352-2787B5F68897
  63C35BFD-E134-4B5C-8047-12629F8C367B
  C90CEBBE-E91A-4438-A21D-EEFB707A6194
  691927C0-9B2D-4EA9-9F2E-EA59520A20A5
  AA602235-4216-4B15-AA1A-48FEA48F7A25
  84FAF932-2C0B-4FCF-ADDB-C728929951BC
  43F47250-F229-41EC-B37C-2E3DD2B1EA37
  EF57ACCA-EC3E-482C-9C63-2338F5A2249E

#+begin_src lisp
(format nil "[[id:~A]]" (caar (last (organ/db::og-values "edge"))))
#+end_src

#+RESULTS:
: [[id:ffb8be57-d874-4540-9fe0-9efea6559185]]
